apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{"auths":{"registry-1.docker.io":{"username":"${DOCKER_USERNAME}","password":"${DOCKER_PASSWORD}"}}}'