apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: thanos
spec:
  releaseName: thanos
  chartRef:
    kind: OCIRepository
    name: thanos
    namespace: monitoring
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: thanos-values
