---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: loki
spec:
  releaseName: alloy
  chart:
    spec:
      chart: alloy
      version: 0.12.5
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: observability
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: alloy-values
