apiVersion: v1
kind: Secret
metadata:
    name: kube-manager-secrets
    namespace: flux-system
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:qESqOdS54AbC46DX/TnH/RyWdVAuszEFon+NPq1QBs9XTaQKg9EJjkjl0KqnValtaY29fLSxedXRQL6IL2OJoykrlQHk9cUM035jW6u9uCASjKjmlVfAhCoQ/2RC1uiPMdnc0nYc+C1JLtug9mI4xV8KTtlahols8Tx4VxtgTXKOCfwcwgg2nXMUxLqWveO/WjpzM8bo7VKBXy7pYLPbiJxpIQl/cdu61GIuD/7xvlWurTqo1hfA6sXDrl4gMm+1jn7GcqtTaZqiShXkLQI7aNvRzfWRBfb7wLcp87faojWD3QE6WGMM5b2YWC88TYuMT5NtAqur/HAOGsvXWy5gMeAyo5y6PQK6l6JEpBnKR+ihKRm2zJJxYCHAtpd1I7dfcapJIQ==,iv:T399tpHlPiZYi9n5Lfrq/cEzcRVMCwiAXVxn6whC2QQ=,tag:6xPqArXHR0abV0X0hoUpiA==,type:str]
sops:
    lastmodified: "2026-05-29T07:56:36Z"
    mac: ENC[AES256_GCM,data:gwJCl489gNtW/K3TT67jeROGrTX7gwePJhxJ1Q+YY6Ao8HrVHVJs+NRE0xFPSBJOE5w9W7WfRnGf0C5kEqx0XZTDDS+Ol+DJxdEGgRGhN9AbR6G9K1tAWwZl9vpN0NNjsK1PbuN/adV/c20ZCOf4ZL/X8Mpqz2M1TNwdLAz4PTw=,iv:RqwMSUwy5g5Byq3jEFynyLikgljgDy96xjkp+9DqklA=,tag:e2wFSnUNNgMtSqVOwvnDuw==,type:str]
    pgp:
        - created_at: "2026-05-29T07:56:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3McSkAh3rFhAQ/8CNyxDD34luHQLhkb8zBaOLGxzcww0Sv0WdNjoVc9Y6Ih
            gsT/c+Kz1SBZ1GsAnN8j/41wOG/vQrn54wk7pLGEgMKbissP0Ig3hwti2iFwJM4m
            I5R0a/ONHV24HqZUSyNyH0maH3C8rjjpgzv+1KNskyVA+3vYnf/ZsRq2dMd/bcTk
            9nSSc28MR9uKpztaNBAdwqgNPk6S6vXra3EUPa4lcmCcQupBjlYd6NkNOwuFVgxF
            IbHh9DM6+JuISPVRYXzHGun0EeN26DfIwos2k7CfzUCMaCV1gc/yP674OUZfoO0C
            5vJnkYj9OuxxNGVc2jnPLjaLlnX9kwvapbt2IkLioGt9W/5pybQuOIcQAa1gVVlz
            RuU6OfCW0VD32bCow/KyJZNGCa9qv9ClhETgXUIL6fCyEUXzaxRnuES3FCOcRBX0
            kg9J7ySKdPbLgZGJsTxsq1IiLyH43EhYObRPjV4lrqAYdxd5FhxtZsciG6cGi9e2
            ZVVzrVCtmkhD2ESa5NGLKEnFxZ1QislitG4f7oIua4UXZStm8WHSb3gzwTGDkkzc
            SJC1AVZZT8/sfZJh8xOrDe4M2ytMXyaKrExcsvQY3UvnrDoIA/EcNvFDt9VkGmHa
            sJzO6X9c8OQeeO8wZK7QAxbZQoXWYkyGNyMcdhMSW3nwkpMAyZb6D/h4NVXqHOzU
            aAEJAhARD5xtaXe+Y5dwc2/lp/8Rgw7nd7If8jDxbTpaCjyD/dAH3OS6wrUiKXgQ
            YvphzQMM0v83wAhOSbFD2kZvhtPVZlDzxVry+QzN13D7nDXTwxuZFnJodDwb3Jjm
            AS9FDOgaQS4u
            =r8ed
            -----END PGP MESSAGE-----
          fp: EF552EBA773641B396D26658E1F56350C447581E
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
