apiVersion: v1
kind: Secret
metadata:
    name: kube-manager-secrets
    namespace: flux-system
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:4V0sRnVFJfFluh0yIHuLXhSCjcBkSXqZnqEieQN0hQfPwF9MdsmcOv8SpwXvLFO3kC5+E/tqwCq1QeVkGegJ/qdENLQszryt912tOHyHQ6IBVAp6Ctdm3UZiizyyo68qGXkeOaKDQrer4Ofju1y+7yGZ1xlk6ZBewgdHH7V2k6KN2Eah/brX01iSdB9tgYAExfYMt+Dnq2+/BuhseKpgmuNo9vty4nqO1peEekVyZ5isdt/s5XsTyWTSw2BpNXJWT6AEUYUBqQT72ayCWdFbFhL2GVqJLvHinmpUGdUbXBksECo1XmTjpgD8MShzH7Tq16N5IH9hEU2o5cy/D1E+wLOaGDk0/REcN9UaGkNWJJwT07LDHhKuakMC/8Z0gv40bwkm/aaTfwd8b+BRyR+K9mbQZm/0Z+Qpu+9XC9EWAMwmAHnPIPlQlpB4WcYMsq+G7KX6XeAN9baqd12TqM9zd7gGPAe54Hy4jOs97yoq6KSiwLJ33qnk7fJzhQHzDk5XIm+67RmNqBiSf3+ynwGU34xDS9mnbt7hbhNpDglPyeJ8ppqsgQ3YL7sprSYX1Gtm85EX2QIJSrs2Nb3UcygEPEZrS+ku9GV/cBLEbAZxYzZhu2bj74BG3Rm+rDrnBGU2nqJnJZld1npo,iv:kRCP7QlFBjtRxKb4Vuzdq46Ji1BQgjmPkW6AvmT+uGI=,tag:h53EUosbLW1Pu3YpASLO2A==,type:str]
sops:
    lastmodified: "2026-03-02T09:44:19Z"
    mac: ENC[AES256_GCM,data:8vIm2N5nrWufeJpzAnsdB13eQd+S7rypcbTIFXFEINv9k1FyH5qfnVD1dFNwmbZv4bEwE4hP80wCvWwZaxB1IpwM/JlvmaZT8eSRAvrHNgJoOUagBYd0F8nj6TY5KeNIr2063fHuOBeLBvOjvMSX23eYf7JObPSsyGtRc9lFZgY=,iv:9P5ovqFfGg0yykvbQd2eBhT8SwlclkZMDkJnPnFhKWs=,tag:AQ04+TO02yZWXHSbEXBm+A==,type:str]
    pgp:
        - created_at: "2026-03-02T09:44:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3McSkAh3rFhAQ//V504hBQAfSWXoJLAIzlvYw7vYhOXk0SBCz03WXUqcKQA
            C7OHrtswAa99nWxcSmazE78QzUclPJb+SlNd+vT5QYuEdUdQ8cDGALmKM+mpf7GV
            kFV4oNykMB0tNJ0hnlHAyBwY13XM/tGP3zi4qg7PLzikAz+gngAep94lB7H049xY
            l8/BmqIEG4aurE6nhaVRcmsOqV5rd1c2dndJ9mhDR1oJOXqQ79uYxqo9xzS+SF1k
            z9ezxjDXOIMxox09tlJLT3770B2g7qZ9SJUOMwDhNrKTRqQ2LaEcJow3G9UYZTBL
            ZnR4/RgB4TUu/qboov/o84QZOOV/DtxxBMW3jri1p6/at61tszuAdfTLBgtkrocw
            M1ULlo493APlzwktvwIk9GpScfW0VGZrNG6jjqzjVXB5N10us1XPDGHE5iKIpzt5
            Ov9u2+f2cFzy0YFWMZ+qrqEHLcBrTDg1666xi5kJ4Aswe98stiv5tq19gUjL2jgs
            l/+hNHRG4TF6kQjHhw7sEPWOtMDpj+VJztbhCZHRES/WvS1x9rYOzhqJ0WcfWM+s
            KNrzZPg6NLjRIlXEoXfS3oSKXD8n1x3i92yqS4RJOVOiOAtbnh/gtfMMcjLQsq+e
            hkU/yKgjRTalL+hBK/MGucK0XY94egipQKviVGZH0sw2BTLzGKJ5v1OKZVK72eTU
            aAEJAhDsvDoRsaV1w0a9Rx/FWQoD9cxEslm4Hc9re2X3Ax+aQY0J4F/Fl4/Wuh9/
            twCNcwL/NiT+plj9JnmUkrdhrVVOZ93i10p4vCabxr85lGxaw045OhXOlyQewrcC
            EH0WPi5+pVdR
            =JYqX
            -----END PGP MESSAGE-----
          fp: EF552EBA773641B396D26658E1F56350C447581E
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
