apiVersion: v1
kind: Secret
metadata:
    name: kube-manager-secrets
    namespace: flux-system
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:FwyLJgvoLStqp9sJcnTa8KjzQALUX86MJFCyrBrytAyrg4NUD8QO+nRalD2ZUns3IOSglk5ZJBM7hP6sQZqynjqHxv26w+WI7QnPqAuqU+19fWDWEeDYhvNNDbKiM8Qkktf4pjs1mU9aixLOg4hDvTeH7QwE347qQy7oi7GeVadcMHjdoZvLK7+Rn3AEnezI9rlDvbx5784ORSwVf7vUeKwnbySm/7T/aB3QlH8Yfb2xkQyPGKv6VXiz4iKE6dTi9tNYmxlpFiPhl6p9KAwl8Qii8A5+vUU8IvUzfM2qZLnS2V6fKQTag+hHnk04EO7sPcimkjTguZGq9jVXIrWxDUQCT+838AKigs310CwHwuwsYLXg5S1Xp7YHW4dL9OFH2J5NuYQ1qFzPci3jGDykP28M9n5dgicXP4H3rx7PsskE9zbGvn+RPkFoNshX35LLjlcfofRAQ/zI1YgqdPxTBMaPv2Q/FS6/pFKYmjLFirHxW3Sw/181R8C8WnRMNXkCOiUWrD4DIg+l8zuRsBNRdBbp+WM5mqYDu0cJMq652vEY0woHzfn7S6WUi+U/9GPD+zvuF5YXvk83bqQdzdm9EOSDt5iTaLad4CYz7g9jFNNkA6ffRaS8OhQjKgGma2bcuSsu5OwZzg==,iv:VD6Z/ymUMyZqY84Arwei1ks171oxU/elMBnLatH+vjI=,tag:pElqkfFRukezhfRzwg08iA==,type:str]
sops:
    lastmodified: "2026-03-04T10:36:16Z"
    mac: ENC[AES256_GCM,data:tBFR4medfuoi2JQCeK+pnJpgccFSTnwHA+ACdVnLtie5R3o/QTi7AqveA2M8pduxGnRBsWb4A3JbLW2VxzmVn2h0d8VboC2mwla9Pp7r/O4LyUoH4cGRg80ji0KGL5EQfSt1EUory7e4XF39NQl0qgGXh6igbZz5/rKFe1/Pb+Q=,iv:hLyAmm5N+z/HDQFwoAn3Nq+SdV8PrFChql99AU/fVTs=,tag:WUUCi3ZLXeDzMAOsEdBWDg==,type:str]
    pgp:
        - created_at: "2026-03-04T10:36:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3McSkAh3rFhAQ//S+wj3SaPtvzdprDZ5+Tpt+pnmQFuS0QCQfybY65rHP9f
            rOAf5aiAvedbLOeeqdtr9MfBOb7A+k0hs3pNQUCbIsQZRz06RUuzKvxgvc/0qjYK
            ErB8h9z8zQeHNtbWqCKmqG3AtaqBBBvwWQgqEBHaMrcZbR4PEUlLUrWn+DOFQ46g
            iQdRYNvmeMhndBQVRh4vyYqek867giP3Hq+5W/Ml6rJMkgWP1DMx36xYIwnu1bmc
            qh8amcyc3XIFj504u402n/EVLq+X4bIdY0M+xcrXNVZz/y8zVoH+f/lmVgaapVbg
            3cvpLIu6dVT+rITOzzX9Uc6mkCdej4Ms5IbHrTYH4twwOphUpNEpEOk6cUEisLfP
            aEhCoO1WmelEmXkDQ5vvAivleHxJ/lzaefMG1c/Y3ZKMC+hjyY4x2ZNcs7L0HQe2
            ZvSfOfakJfYd34Yoxd7J2H/S3H8H9PsdUyQM6r0x2pm7xMtSX6cJWK72xnRwXV1f
            fUG65Twe8FWs91k+VdIaqdn2kCQ31YV5LtgsCLT2tX3jVxmvE0rp8MrC5a3/H29s
            Qk81czHZuYNN6XMRGQoAG1YIVVoMijRoqvwKR7GUDW3eI+0Qz9cSx/qCIhfhPnKT
            OR9zC+11b9j6JhUHNzSbeYxuGrA359hBDI9iQJ7Zclsv/KJWHrMkuFbboAgGc3jU
            ZgEJAhB33toxAO8ltQmH/f/laj/FGegrQKg10gQIPT/wmXdZF9bT+D0hMyLmF1Kb
            Azfzlgb61CcAt6a8W0vcwYnV6FUWKLzVuly6FtodqxOswychBlJh3J32ZiP0ZV7v
            B0NYvLVtHw==
            =caJ0
            -----END PGP MESSAGE-----
          fp: EF552EBA773641B396D26658E1F56350C447581E
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
