apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
spec:
  releaseName: velero
  chart:
    spec:
      chart: velero
      version: 8.7.0
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: velero
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: velero-values
