apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-manager
spec:
  interval: 5m
  targetNamespace: kube-manager
  chart:
    spec:
      chart: kube-manager
      sourceRef:
        kind: HelmRepository
        name: kube-manager
        namespace: flux-system
      version: "1.0.0"
  install:
    createNamespace: true
  upgrade:
    cleanupOnFail: true
  dependsOn:
    - name: postgres
      namespace: kube-manager
    - name: valkey
      namespace: kube-manager
  values:
    global:
      namespace: kube-manager
    image:
      tag: ""
      pullPolicy: Always
    dockerRegistry:
      enabled: true
      server: docker.io
    app:
      enabled: true
      replicaCount: 3
      servicePort: 8000
      resources:
        limits:
          cpu: "1"
          memory: 1.5Gi
        requests:
          cpu: 500m
          memory: 512Mi
    celeryWorker:
      enabled: true
      replicaCount: 2
      resources:
        limits:
          cpu: "2"
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 512Mi
    celeryBeat:
      enabled: true
      replicaCount: 1
      resources:
        limits:
          cpu: "500m"
          memory: 512Mi
        requests:
          cpu: 200m
          memory: 256Mi
    nodeSelector: {}
    tolerations: []
    affinity: {}
  valuesFrom:
    - kind: ConfigMap
      name: kube-manager-values
      valuesKey: values.yaml
    - kind: Secret
      name: kube-manager-secrets
      valuesKey: values.yaml
