apiVersion: v1
kind: Secret
metadata:
    name: kube-manager-secrets
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:sHz8bKFi30bi5M+adY26Bt46s58HP2IKSji7R8bda4aM4bEQ/3i4J0jdxuEWSXk9pB7em3mCHjxsWlF15ICnVeWr7XEibEihGKIui2QFK0NF8SruaN1CEaLBG/w7tKLyhJW8WjnzqFLIK6WhmB7TRa4pDrGhqx0YmspomV9kBZUO0EMqfN2kIGN7o4IWxOiS/QyLkXaVYXJVn+Qs1U5NTxlXRtcrdxQPMzp2Bpr7P0VJtZYPmJEktdZhMV9+SC/EdgRzG36Ia0/rkTg0Pc7GKULzNMfAZlpe8GZi1fiEOEOBa6DpxLgvO1Kdh+yD77AN5CblEpFEtSmM87wmqc0qMrtJ55Kf3d/0miozHcKBo06174oDI5hC50BAQWWYS7IdlFWzoTuEUhkEAi0U70ZytfPNN6UXS63y60Ink62nyoZLtRek4+4pZA+4Hc7PmaBrBm7fs2heVUwJ7q8+in4hXwGffhEiY1MgsKyjF4273rznBJr5BLKb+NQcywMDuIHfJdw258h8ZKz0Wy4pPlv3khIKdTiv+eXHjnW5MR0Zhzs0yW8CWIdoq0jzWn7w0b8PNj9vlsTg1uzWu9ViHzfCp3zL0nnIMkbjlsJkbu/SzwXqad4GMsEgko5UFcutlA6N7I7XHNCx+g1RsClAEaxCXEykdhEumwPOqJapGmAdE+/koJtEEnTx1gdjFNy+OBwIJGnlHmEzatWpI/I2W9TQ9My9KNIYcdPqIZG0gmdjDnAaXTUbKsWNE3hKo4ko0QpJJOPyLU9y/8+HMtffvGxe8g4LlYSf0doqN8Q7Uwk4CA==,iv:Ts0gxszlNxZyAye75jlSa5DqDwzQxvPAJvUnmMj/Pa8=,tag:PstZ9kppSVCfoaQVHED5Rg==,type:str]
sops:
    lastmodified: "2026-02-13T09:01:33Z"
    mac: ENC[AES256_GCM,data:Xy9ejmoL5ixMaWZir+/L35QVLGc2yg/TryQScB6uCamxZoOJPC94k+I4dkoU+4681m2ZZp0B4MGTjc9YhPnd+dwPX2eSrpqgN5k4yN/temSbNf9yaF7QuFh0hc1Z2Vye8VuW2VeRXcm/lVHnjR7qAJFkIwaANBNp68Prp0/4lzU=,iv:jKRtxz61Fru8C0hHAfYUD8PiZvGxGww8Asit5J43jB8=,tag:yaQzndNsNKyyC4NYC1YRzw==,type:str]
    pgp:
        - created_at: "2026-02-13T09:01:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3McSkAh3rFhAQ/8CeURb1n6R8xySXcmpW1fx/HFGjSwKKPGtRHHik1VU5zS
            BZaem2fAvhEOgJXD4FH4GXIoR96cUsIKVdM3w/avm11vnFQ4EOxjmNNAeAPk5asg
            d5OOjr4Uw3GOYW3OFo5dCaTrdZwufDPmUqC73JwM29tMMvVanTW05diJsPjYFvUV
            ttg3Eg/sUKVvy+EwRuWug+Q1f25wz+ScadcFd88wqernIufmknkNTBqopOcF99fz
            um3f77nDJ3+5BUqJY1dkLW3A04DWMIATlbZ6Qefz/EoYkoCsZsPzJv7pfFbb9EDG
            w0WEsd/ybAkBVatB9sr7LIPRABavRDIjaQTf4vEaa0s4n5wz+eBX2cggdGqQL5MM
            tCdwqKMOAtQslr3B6Ijrr6bHal89R4Y0mIptdYJ16ezSa4UHQja7rBb/K6sIatts
            Mr4WHmbYrDOjTXSSB7jaRWXF8zfyAUZexckr6ixorRw0g2p/zadhRB4mK0x7ie3x
            fFMjSO2kCN5vjFi19Q2vcmpOyCeWbNb6cL2Q5APNw6gA30gi2yTBIzP9SQ/wiN4Q
            tUDiIB3e0yz/B1SqMpIMqHDza3mJvvjYlSN2FGk3s+foREUaoOSceDn/xOZb66Br
            Rp4Z8e786jg1N/xmJa88zTOkjUppJuAlFn9j4PwteRwdX6wuwHbueONgID/sJpXU
            aAEJAhCkZ5OtgkrXbk32DlJwcpFEpXr3NCA4NLsqYXqjdqm9ORBDBWDJT7/hXKDw
            /PghNnMJlJ23mb2Mwj5viw+S89QRnOc64sl5ZvSvnx4VOOIey5Hkyxs1sUUDOhma
            O6p7z4Vfw4Xy
            =6mBP
            -----END PGP MESSAGE-----
          fp: EF552EBA773641B396D26658E1F56350C447581E
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
