apiVersion: v1
kind: Secret
metadata:
    name: kube-manager-secrets
    namespace: flux-system
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:X4SyByysnmRtNvjLNLCiKrXe/ugexqemjNWgsnOvodniD7aFfb+aaYZCRPewqCW5uJpmQ6ZEHy87VAzyHh6BIUk67CdiWn++Ez2Pu94Fwkffm7jmC0Raxfq5Twwmd632inN5Ror7MgtbHrrI23xX9xQWu1pR+IZq99s1xQLRSm5+mLXrmVtHAUh9CD+iyV1ySl7lgqua4K7DwPUFpKZvFTKwJnqSN03Fpy226KcD0YKnTA7+xmzCrTcTH8R7wMEg4EClhNHz1+omm8HXb7E4vSCadpT8wq6CmIAuvV5vb4rPYIoMQ4xnUmSdV+IVXfGte3GE2i6dknzdEgDwfquBmTSDf1th+M/C+fSkIgXJeSax/A+pez8N5koKqI2UCZZspWkl1xFO0k80VULxaex6Z/K63YQHyCY5YCr7KIn7ZzkRREyTdZ1cMW+6S3+jDTTQH/aQ5peP3EkeoUXUtdBJlvR6f9vXma7Rkox7gNjHSG5Agr7IIPXZdu0X/zbwPdZ2loDGlqt2ZnFPDai6g+JMpY07uCOSBwnFd2B5buHkh8lTDawgcsZsPuvy8DAjDwQ4X2BDaSOqhvgTRYJIRJT4JhJXILQFZzUmGRjqztKSDrw4Orj3wAOBgq/cWa1NIm4bA8lcuQp9bk6L0vriUvgG61yHTQ3FBtwEhA3yZ32Djh/MjAdySWyZ5QLpCByVe6bz,iv:9ZtFjAnOp79RBrBZWBqzpzoobJHrFrBPPyBN+kbXqFk=,tag:KVugz8zVzf/8HOb+4HTamA==,type:str]
sops:
    lastmodified: "2026-02-13T12:19:20Z"
    mac: ENC[AES256_GCM,data:W4iI+j3ikBmPZ/IuTH9oAnhTZ9i8JPK8bEsHQgspR3fiebJ+2NcPggjhRnAmoS3dWFqLg+Etr1paer9oQMn/K3wa/okJKBAPN9FA+3mWozkhzPwMhq7YtPHBxDzYHcV0luiDQIY3kLdwGMuzulidHwt3/pggljkA991jld6YYqI=,iv:YRpNyVItx6+KT0Z0IEZ6b8CqEDRpObXRGa3bSAfeGhI=,tag:+44UxVGupyfe0w/YmgIoqQ==,type:str]
    pgp:
        - created_at: "2026-02-13T12:19:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3McSkAh3rFhARAAh+PvakXlaE/q5t3nbfxUcTahpnM5ZuGMmvhX1oaUiThy
            1Ufpxyscbprl2ITBpsYQxAg7icNappwc82IoyPitg9O1HKSCc0DCOH/dC1Yh4t5R
            WDypxOMUzKmVjG6VXR7S5i5aecB7QxsgLKdIgkORbEmOc6Cw6Aa/riGtNRIc60F2
            T/ECqzUEyXGDapf4vvdHaTEGE8Q3Sw339c60y2cosW5V1+5pg/mfsPPeYhPJxYhL
            wM4AQxBjCN94rPoVfDV7n3ZxQcG+ppytYwPD4SdVkTmskjKc7UhJNF1H5g2MRQxD
            zRcoz3upC6sZVyWKMPVtsLsXDVntA/LNptP62RmvfEZBRyeXDIW71XcqOrO7w+og
            5Zb0olyXH8XiVA1/fVoGSkqizu1zfzKM6YBDHmgn62xBzAQZetBUh+Gf6xJNIiqC
            RpH/sfC7ud+1x9hcz/8dvSb22i/JryLFm1fBu7XWfPiLCkb8KpfPXd54TxLdFJxb
            VXj9eBzLGbSQPB8OR2j49arJm6EdPJg5N6A+j2ygqlEJ+hgdIEx/K+Fv+wreNPH3
            KqMvqXJWwrM8Dilh5uQMCW954Hsai7nBLgEeXMOe5pdC7Yi401H8b2ECzBZX/wBN
            roFqSk3wgQLemIWNzqxP0eD1m49oIAwMfQMn/j73zcBihnZGVD3IgFhcIAqz3gTU
            aAEJAhCuINzQTnJg4hwikInsZHM/69ioPIwSN9u2TW+O8qV3wUIdBEf5ea6uM6Ys
            2XSvcHJqUKUS1dj898EQUeAjIW0beAtJ200xLr5udTtZwGAEC9LWo0dNgTi6xPMU
            P2ONn7V55s9q
            =g6uB
            -----END PGP MESSAGE-----
          fp: EF552EBA773641B396D26658E1F56350C447581E
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
