apiVersion: v1
kind: Secret
metadata:
    name: kube-manager-secrets
    namespace: flux-system
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:2KYrxBZj5nFvy7lJj3znG//LtSgMO4DiHArVKF+/e0My+O2V+2Dd2CCKtAtZYPyOGIBfHPjIouf1Cs2StvvbHw2PBVP1Gr/IsTem6OhD1V4qfq/F8vej22PjI86p2CxEWRM26SeORVIigNCofoUHnhsTBOy4FYT7busXM7kCbKv5puc/jUC91IUTjkJQ99ZhBeORgvYRBymwSaTNL+RYh3QfdcOZDpDx/kVuPg1FL7Ia5fglxdsLTzxQTgTlc4lQRqFz23vwTBwisQBEIDlb2Y++oSqBTSAw3X4UzbGFZyp2MFt9zhHJqTsMPgoe5mchxSeQaEuNUHKJB3XpKrJOg2a3Q6yTKeRuTif1Omra0Zv/76vcauXAGx8Zjlsb7ivJsF8xFG/dq3swKEDHDVm0Sc/0juIsPsHiJ+siryqirPilna674jV5riobnJmNhVfW3a4ibLpVzhmdVu/zDGpMuLT/HeYP4/D3p3Ugo6argSHSkhuCKVFy0RdCoXWOpKe4fw8pAsYYoL5jDha8+VL8NuYNk0GkXIOnJ/UzI/5mJY4XPqCmGQJvx2n1IVM1r0Ukhu64hJDO6K9TnFARo7D9wry15kzaRvB6x6wPuK3yNbPU0S+CNfbzT5jLZOX8qQnmqZJRdnflXg4+utG0LNg0bYJEiL07ttRrPXKvabzhxlQh4RIneaNKWBGuyt4N2iM+p56L1T2/sT45giHFPXWZEFuw6GwhoglocAnaci6y7df/bcED0f9N20MvNkHzjEc4BztWWuosptJILj2UqNNg0vh0uGBmGIkybREpE9ZynA==,iv:K1Zb+ndY1HdBO9TET+KpKlFUa6VsPgc+YjbOiBdxDeI=,tag:xcRdJkQOVwv4kmstqXhH1Q==,type:str]
sops:
    lastmodified: "2026-02-13T09:31:32Z"
    mac: ENC[AES256_GCM,data:NNwx8mRXkDoh5YQVADlC2teafEOQyVDARueaStalgiBwTJTi1fJMVgNGzL4lVKOE8u9SiZqvM+NKWNVYq+XeNMeZZ9IBDtrhru4rOPb0U/LL+SF3JVyiQyitMpL193f2p8m5zILxONsvRrOOz+D7cMrMx2L6UqnDAt7xIe1GDt0=,iv:0LFSfFvUykB7woVKWobt3TaCaqKpjG30PtDvtXLxiAw=,tag:TIGHo9rQhiK6Yx6KTtme0w==,type:str]
    pgp:
        - created_at: "2026-02-13T09:31:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3McSkAh3rFhAQ//SNjADtPLfXZwOQE6lghJO8AYDAhkgjRd5FHqdhQWEdJL
            r6sQ4LU7BNHmkDzxIGswrCw9kEted660aSKLEFCygMHBKvcqieXpvkr3T8G7Nu7A
            3N3I/W2RyuXf7QCcD+ekYiZVLVRl1YvjHbBEoNQDjNlx0NN6LhDzwCkhqtBlkNPO
            KNo0/jueAGXoOcB0uZ1huvPlM43wgEiTIfn16HKm/xSR2W4GyOvmYG8pYQ57C3MK
            R/3dfDOE23b86Hh1dyTDyrnCYc8ZeoNRjLSi8kKRNw/GuorEAlMgxxpOwuwgEd0g
            zeOXa4c2vxJ0n+8YegZ/NAGf1SUr2hJyfnrmUYFeVKRGrvpX69EzmEg1RurZt213
            wLm0RGfsNG2iE2xnrf7bMyQxLs05xUbGjG8RTgVqOnnCZqV0tuMn2Co32Q7gUVzf
            5QfX2zcnCQw7L7l+imEVLmA5rsgEs0xXbQP+Co8TDbC30ag8tHZ3O3Jod+ORhS+w
            q211JT4qLuYP5SBGtOg3Su+USfs+TXz2n/36wAJuJVzYMK7TE8j9TaiQSI2xqdqa
            bln0Kbr9k79huEkJK2eRT6b/5rpbITibl7pO/nedIYbVIBW+i3kgLA25Rs0ZamMY
            NLNVXTspPmSeA1wiVg5jTN6D8xawWLFmJIeWb+CMXEF7nItSgO7Qdlyi90a9tW3U
            aAEJAhCFwf4EPvfCBUM2LQRg4LeBdfqlX7dvUCMi8wa1XDbLGpZTSkCqNJIwfPHZ
            2xBEqm4Xi9SQTBh4v01YTAaxXQggz7PUCsqqQPa85M5TwpO/rjFolMyhW+aCcejY
            VhlVmv4R3ZJu
            =hE7W
            -----END PGP MESSAGE-----
          fp: EF552EBA773641B396D26658E1F56350C447581E
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
