apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-manager-app
  namespace: ${ENVIRONMENT}
  labels:
    app.kubernetes.io/name: kube-manager
    app.kubernetes.io/component: app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-manager
      app.kubernetes.io/component: app
  namespaceSelector:
    matchNames:
      - ${ENVIRONMENT}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-manager-celery-exporter
  namespace: ${ENVIRONMENT}
  labels:
    app.kubernetes.io/name: kube-manager
    app.kubernetes.io/component: celery-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-manager
      app.kubernetes.io/component: celery-exporter
  namespaceSelector:
    matchNames:
      - ${ENVIRONMENT}
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s