apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kube-manager
  namespace: ${ENVIRONMENT}
spec:
  hosts:
    - "${HOST}"
  gateways:
    - istio-ingress/public-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: kube-manager
            port:
              number: 8000
