apiVersion: v1
kind: ConfigMap
metadata:
    name: environment-secrets
    namespace: flux-system
    annotations:
        kustomize.toolkit.fluxcd.io/ssa: merge
data:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:A5BTdGnKXFSn3Cq/MSn+Rf3qC35CB45imufiG5+XvYvMxDWIShveKA==,iv:DICUnCj26Fx0M9PnCRzkwlyIAa7CNipT5bzJ8DWBTVQ=,tag:C3HAYTTG3bbpFyH10vzbNQ==,type:str]
    VALKEY_PASSWORD: ENC[AES256_GCM,data:mfqt/zfLyvG7l05RUCfa3veI1V7RjamEs1ApnUvQLN4DrK030N6nrX3iRQ==,iv:yx/pSSYyV/scdeTCrC5m/UYJBfjEVP0lBDno7X1M2kI=,tag:bWpXYBhxCmf2VXs/mVakcA==,type:str]
    KIALI_SIGNING_KEY: ENC[AES256_GCM,data:lisRZtOTY8FGIGvW1Ue9AHMOF/JjLC2iWLosu3RswVREZKp9o5Epaky18w==,iv:kDzYqens3bfarcGQF/FoHbTxnGH3RStbv7Con65Wiwo=,tag:bZCjx7g0PcR4uvmxQPKDYQ==,type:str]
    #ENC[AES256_GCM,data:TExA81nbFUY2Mg==,iv:ZKMh3GcSTBWVZFxrn6Fbc1/HuMVl3FdYHgTDvdEXpb4=,tag:T8Qa9rULFgdefEXcKO3OlQ==,type:comment]
    DATABASE_USERNAME: ENC[AES256_GCM,data:biWkgJyccOo=,iv:mqVtWXCsfVsG44fJLxoTKMVxWhTtdhNaKQanBv/y1Jg=,tag:8VUUwHMVV7r3hM2RxIXwjw==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:z6MVQ9f05OOVJwn20NTVLMxKRy8/AviW22XKbQyXqdFNMd2Y/b/GuFqVtQ==,iv:lcPD81GDNzMZsgPzY2poRlEyHzAUBFqhfWwx8kkrMbM=,tag:SchlXQ4MKVexM11tULYKgw==,type:str]
    #ENC[AES256_GCM,data:OviNITYU7HQlPcdWlbEWrFyt,iv:7UUXedrBXYwu9Oft+7ZZMXnrczlwxTGUf/D/p1FeJew=,tag:CVJOZwKK/Z+VoKsO/xFyEQ==,type:comment]
    CNPG_ACCESS_KEY_ID: ENC[AES256_GCM,data:swUewZvijEIyLcjPTvrBv7c3JHU=,iv:jsEGxG+snXsEZ1QN5Voc8PjJzhwWu9ffg+NyE+PUPfE=,tag:woFKAAdmBGlj4TjcgXhdgg==,type:str]
    CNPG_ACCESS_SECRET_KEY: ENC[AES256_GCM,data:yttHE5MLoXhdojbbXaNT4ix4TTar99IEd+9DOrvf5xJhnccuDSwlQA==,iv:uh94BJRz0IDaoXa4VtooHWFJ5e+Qlei4847gc2pab1Q=,tag:g2L8LdL165kzsQkrLQYHtg==,type:str]
    #ENC[AES256_GCM,data:wk0NcN4aA7U+wuFP,iv:HgWfxMrE9VyvEHqwuI55VbiYrPurq4T3/oGrMubbzsE=,tag:LBqHwjl+QscDBJ00azDt4A==,type:comment]
    LOKI_ACCESS_KEY_ID: ENC[AES256_GCM,data:Zm1jP0IoAgWp21fZuk5sSQGim30=,iv:GoRiknfczAHbT5UjPSP5QOk70didCKVwbD0VMsWkAXU=,tag:Bw7/gcXH+LYbHZAJ3XEiiw==,type:str]
    LOKI_ACCESS_SECRET_KEY: ENC[AES256_GCM,data:uloNih5t+bs8omsgy0+fFhwbBq8cAwqIjKJTif2gL/QarnOLa0Wbmw==,iv:xgnP5kp5zB3SvNOVMY+MZ+25mO9Opj9ksMc771ZO0a0=,tag:9LTQoV6/8FA71vYMaZJXvA==,type:str]
    #ENC[AES256_GCM,data:rFG3dhiAe7d006FOFw==,iv:4HR1MAqIhfg5qVNkVnTMWbmTT6/H4CBWpZ56yM7K/30=,tag:KspHUmBzylU9rSEC5iWZ4A==,type:comment]
    TEMPO_S3_ACCESS_KEY: ENC[AES256_GCM,data:oP1sL/pypDIYXHZdpBZ0vwMVmsA=,iv:Zfdf3P3SxDxUiiEJPTlstC032T/iWvF/Z7vqU5VBfMA=,tag:rsN0xXmT0kFo1Nd761kysg==,type:str]
    TEMPO_S3_SECRET_KEY: ENC[AES256_GCM,data:cIjzxvlEXVT5WMREL+y3VGu1iGEZKTiA7v+Ih4r1jHgcoLCqFnNyHQ==,iv:oYXhvQGlqVzeVTgKSLUdYarWQlKJYOOU4107nRGaZf0=,tag:5ZIhBzvns6HNU06y3WVbEg==,type:str]
    #ENC[AES256_GCM,data:pccBHXL06+j8H/GT23Y=,iv:iz+K+oNtkpgR+qtwEVmT216/WuqCzIsK2fhiMINoPxc=,tag:WYK2vKehw4cM4zLhHFhp+Q==,type:comment]
    THANOS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ynLrYGHmlBlBeddhV8nAQoZFow4=,iv:0FGnVgnj63SU44V2QcPkh7H/YwGWw3ZHIN9P7QdEj/w=,tag:zEI0oWZM/pU7rFRqy3PQYw==,type:str]
    THANOS_ACCESS_SECRET_KEY: ENC[AES256_GCM,data:4B/RHZrvLBybqan4SUU3Bq4Y5rrS3lxpKd1HOnwPesreHvruLRC1hg==,iv:QSZNdzckT/hGRE1IfsvCR8/cPP84PaEhUL95KrSRKGw=,tag:cEcaPOCiErJri036KNJuLQ==,type:str]
    #ENC[AES256_GCM,data:qJ6wwmM+fRsBRT73kXVj,iv:z9sR9Rg4RT08Ff6uwUPUlsnTsC5AgyRxlB/WCukFWyQ=,tag:Jby11OIMqkidSuV6yvFhiw==,type:comment]
    GRAFANA_ADMIN_USER: ENC[AES256_GCM,data:GFdvt2I=,iv:YkybMU00IV+VnzNd9tCMaix4OSg1wNzsWfrYhDGk/IA=,tag:XbcT/7XtcuJ5sbxI8kIGPQ==,type:str]
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:gdWKMNGpFW6YIdAVB7JjN76c1Fkv8J/nGBezucyGeAdDmD3ykewhK6UXsQ==,iv:AREsy9Rl7V3ccwNcmFplR03QY3rR5sjvIZ+6uUc3sYQ=,tag:a5+67uAykp+S3/Mnaf4MFA==,type:str]
    GRAFANA_AUTH_CLIENT_ID: null
    GRAFANA_AUTH_CLIENT_SECRET: null
    #ENC[AES256_GCM,data:k6BfB63a3tr6rKDtZQiTAOWl/QkNUTc=,iv:W0P1u8Qr+d0wCkfMHgk6X4bDk82+6arB9Nhdihdlz2k=,tag:fPsvdgNfhZ/nXkEfi00g2Q==,type:comment]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:Wcrrb+3WLGMKEEtWoFC0DIYf8ZH/P27CWwGZV9gj6hsBhGaYcFEFxgJ9rRtRdQ==,iv:4W/qrTOrAAsRHrs5SsG3nesQfT4IC5+CqHkbknaLTyE=,tag:65/jZ3wjqy2oRYmbu5dEaQ==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:A/d1cHUdPTXx8EY=,iv:innM5+7PUblRpYsVuBpbHkPqmRguFvuF4bxxskGKoJA=,tag:/gPgVcUIDps76j5YNlgsbQ==,type:str]
sops:
    lastmodified: "2026-03-04T13:17:23Z"
    mac: ENC[AES256_GCM,data:hDxG1MrlZKwt1H8VQ2nitD+K8sNLPhNq+fqZJH3QYH62se+MVicZ9/WFMpZFp0+lTs2kyf+XBdq1lq2Vc12s+ApBHHxTcVR3U4AZHHCOfVTknDRZ8OzecAG2aIvzzOq20d5cxSHtcFkf1XmSrTL2dNWQkg5dYyyAu0lEhzUdM1U=,iv:ymk1SuQlEXO7TJ4xIOk2jAbDqJUVGl8zUYhnTVY9SQg=,tag:ZshAe1fvBeWoWeRmd4F7qQ==,type:str]
    pgp:
        - created_at: "2026-03-04T13:17:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3McSkAh3rFhARAAj6Kv2xjKTKU2u8EaqVpLQn8ZqL6WUn5Jpxxpb15FQDPb
            Oxqr85T+hOf/1t2mtCplVYvOu+6A8tNI5dPWtL/vrVgzgKJcmUjJFq9H8+ZuVpWF
            jLyUGza8lnuALM0PozBi4rPVtUAK1N/HYRD1RjM7kLLj7K4sYiojrjJCr9DuA5f+
            CDdf7yja7FtbKnIpScfltXhrLY8ySebIr3vkMKDfMR1qgZYDDJvjPoiTIB5hXRH1
            1zb3xSz3UQ86nu+yxWVaylb5kc8XGtw0i88C+u3nRSiBWAiFC6nSgdwXR0K6p7s3
            s8pi1IQB/LBiCft7YGvKfUKYP5NM844Odtd7m8vO8t0gKA+NAz8Fk8gv1QUz2wCg
            cChzwuzFSEJSDbFyDVo185tYT1BhUuyLmKPoLvgKO4e0zEW4b2I910uK9bwxoyWR
            ROm+ItwDS+A3cytE2WsXHsUwg7U1Nt/ETepNRZkWg1UFpaBJDXVGYBUwvKsUEEco
            OtsQf5vKvzrQly+TY6fj8nlG3dmFYZJwetc0y/yZYsxbz4iAX2mH5aHGWhxfDYSm
            QUX63pf2os77rEObAL8W+mGXpGb+LTp6aNhtH9UJPIse/EHe2YW47ikxm3Jc5kij
            UTfpZBwhxXwHTuD1olJ7VCcpFzFwg5IuzVHzeadQkKJHgIqGAqFCX+mflAaqKWTU
            aAEJAhCEF5KRsR40esRx7uzI2ygTdQwYjt/4hkeQhq2BoMIc3/5LacXpsCNje6dg
            LCjX8ZP+fnkSzeOFqk8lufCrLFvZYUKT4mCPR2sJQHoYcrmbzMQ6I8UV/9tpZ0La
            JOXEsZF3mw/B
            =C14O
            -----END PGP MESSAGE-----
          fp: EF552EBA773641B396D26658E1F56350C447581E
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
