apiVersion: v1
kind: ConfigMap
metadata:
    name: environment-secrets
    namespace: flux-system
    annotations:
        kustomize.toolkit.fluxcd.io/ssa: merge
data:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:9gZ8SK35YKtpY9Jszfijxg9jXFch5mg6oEVMqWe2qUOCXfh0fKas0Q==,iv:ZTjoCA4wpca3SubZr8iS449H5EhPcwOUDTzxjHMmvms=,tag:u7d3NF+GXIjTfzur+JH3cQ==,type:str]
    VALKEY_PASSWORD: ENC[AES256_GCM,data:If91f9S5jiLj33drh5nj+Lfv5au/JQ==,iv:ttRw0PuixoUx1hameOi0TUgITtxoXhxGv+6eEtKVX4k=,tag:z0jElPf2knbqcYjwsTiW+Q==,type:str]
    KIALI_SIGNING_KEY: ENC[AES256_GCM,data:Pf8oty38eOqtlDRTXByoS/RgwO8V+w==,iv:+3AcoXEPFmjF/WvPJzFiOncJGi76WefNercH6ZFDUbs=,tag:KLIu1R7y6Xsm/+QVRxmYnA==,type:str]
    #ENC[AES256_GCM,data:BlOoP5a/WJiUug==,iv:SOOODNrfBXtK5kiMfnXeGHFIx3b7Lr8ZLVjxSurD3pM=,tag:A8DEBfETASWnoI8LvN1CeQ==,type:comment]
    DATABASE_USERNAME: ENC[AES256_GCM,data:sR3y1owCD8Q=,iv:3qDioHIoRToG0cbaXqcRARaWYxlOo9qcn+q2cED6CzM=,tag:XcIcYjMWrGweLweXDGWbvA==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:fqjHjP2K8OYjiLADKlJnAA==,iv:oCLwwfesdCPItIM1gu9v2/t/4JjB6Y3BifXVh9Xonuo=,tag:/yjF43yf9XfvdWT0lN22Wg==,type:str]
    #ENC[AES256_GCM,data:4OXpXuAacY1sCfkT4stPNtc+,iv:ygkmsfnVTXBZLcfrOPElnemPYO48/38QuVWftdtuvo4=,tag:rn2eUeYNgWS/4cCbEaoBCA==,type:comment]
    CNPG_ACCESS_KEY_ID: ENC[AES256_GCM,data:SVnrmrBeg3ps9wtjzzTaL65Thk4=,iv:latejXjYnEB5QvSFZylO6BKwcNf4eSbeFm1UBYUj4Rw=,tag:SQQgCAnVUFVf6VQBjpiEvQ==,type:str]
    CNPG_ACCESS_SECRET_KEY: ENC[AES256_GCM,data:gvhWZ+xrXWnmQUH+8S5kPe8aHeuDaffGdHKjU1bhfzjfKC3Cn457bw==,iv:XIH0HrtEqlgefSmntlXIA8FhazVf8F214EVQyvJWU90=,tag:JAI2P6Fo0O7KRxpbUmR5GQ==,type:str]
    #ENC[AES256_GCM,data:o7/M7sEcaCgsW0yC,iv:KRA2dbSlJuxX0PKXXOssfqYl3udHagJCCXTul5Wyzlg=,tag:HXGusKkitrr56kfXakXQzg==,type:comment]
    LOKI_ACCESS_KEY_ID: ENC[AES256_GCM,data:nwzaIRoFKh6PnSbfhZQLLj6c0SY=,iv:irr24RE1jOP9ODvAyJM2wlWANMyXI7tNTH/qUW3vYnY=,tag:2N1PEpOj6yJklMlkM2azbA==,type:str]
    LOKI_ACCESS_SECRET_KEY: ENC[AES256_GCM,data:NtL4C8KdATyH94LMux2QyG7+uPI2+NW69P0U5FAaAhp8FUtxMX00Mw==,iv:xP0QcO7unWYVex/Nqwi0NLRnOfKbNmSxWSIGmjDHRPw=,tag:H4NSPIHxaycw6uM+za9rtQ==,type:str]
    #ENC[AES256_GCM,data:QOxI+aT/BFe8suHtlg==,iv:CqOV3L/Zw2pPwSdysdv1KBXfgzOnCHNzSzYfJA13P3w=,tag:oOEDydd32+o44Zb3M8xSXg==,type:comment]
    TEMPO_S3_ACCESS_KEY: ENC[AES256_GCM,data:/uBmaeApXUWJ8VATEm9UDtrqiW4=,iv:p0FrMzQVmyZg09nq7IfBvS3S08kb+6qOZavfWxJWinE=,tag:8wQbF+H4fSdacXRIQ2WRYA==,type:str]
    TEMPO_S3_SECRET_KEY: ENC[AES256_GCM,data:G7SlMA17bY4g1+68DiZrRvzOfSeq+X3U1PkLbv0H40/qdPekYnojgw==,iv:QLCnQFUfYSs5G4xb0nUFRF4yR+yosx0TQR8QsDTMbP4=,tag:uwXiGW+SIxb72F9L+ekLgA==,type:str]
    #ENC[AES256_GCM,data:CYE0WfayJh/ovol4z3g=,iv:tC8pjPoqb9qXr90EpLS7S6wlquIF+Q7UukUzDaugDtI=,tag:VHdFK9fFpRpxPDXaw7A5aQ==,type:comment]
    THANOS_ACCESS_KEY_ID: ENC[AES256_GCM,data:A+aiiLG1QHiKwxa/Qn+mAIJjbEo=,iv:PxTnFJJfNS5dbywvzKarAzUPZyxHryBEMAZfOwu6IRI=,tag:aOUhaYjdX7GRjnxwNPSSXQ==,type:str]
    THANOS_ACCESS_SECRET_KEY: ENC[AES256_GCM,data:/ZWP0dpth3e/1UASTpc3j2Sz88STwmRdhbUA+NlwYAQJFOXFT+4akQ==,iv:9SwFnQihfPuuu/7WVYEz4fQBbSrmltTtzY1GSYYdc7o=,tag:nQMJWO+iQbaOpzH1yTkLAA==,type:str]
    #ENC[AES256_GCM,data:Z0fO5F88jPrRI7EpIUeF,iv:tUJBqombR2PmxbJ2ZS9fwA4t3fslbgNdvMshleEq110=,tag:dFG/YsLI+jcyQ+Lw9/gsaA==,type:comment]
    GRAFANA_ADMIN_USER: ENC[AES256_GCM,data:N9KXdMA=,iv:jpwVu1YvHL2kJWCqOdyrVXV0Q0eWTd7Mj6xE9lZqqhs=,tag:fBQsJvnE5SvtptppWxJ3MQ==,type:str]
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:N2KFVDjJtf/N3Zrr2DZt+piHLllXKw==,iv:nMoL9361jsuzvEpMk+X381t77Z9BVISxm/kv4S/voCM=,tag:sFkzZlsM84DYITmzAIndqA==,type:str]
    GRAFANA_AUTH_CLIENT_ID: null
    GRAFANA_AUTH_CLIENT_SECRET: null
    #ENC[AES256_GCM,data:9dPA5N5fiv1SE9XGZThBxeJAicaKu2k=,iv:qaZAovhWKhKP3xazSDhCsvNByvW+3EdwiG2Cc2Zu2ZQ=,tag:sbNubvFXO4/jyxxAl60eBg==,type:comment]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:+X4fydk4BVNmQxwchCN5a28B3vCqN8pUDora0quwm1WogXujXc+/jr1wFPdFMg==,iv:16H6xJ5oi8Lgqz2rwP36bQ36CkVr0Ht7asRkS/Qtiso=,tag:f2ElWYq5+YF5L+vmvlguPw==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:3egEhvIz48JFLd8=,iv:ysuOqZTfBllEV0F3AdJFhDQJTWAaxrrxQEoNROpENNo=,tag:4Fh7aFHn+B3e21I84Y9Z6g==,type:str]
sops:
    lastmodified: "2026-03-02T15:21:51Z"
    mac: ENC[AES256_GCM,data:RvK42oR6fhKa92cnZuMuJEdcmdT4bcdqqKAxbXwcDpCV1XZC41+ze49DZ7ivmu/Oj7axKQhe+mFpKSedbfEe9bGxXiY1DDkf3MVTRbm7eHFfSw4gCaYa3W4WIbhad9bX1hN6wud8PU+YOfJdcDbP+osjTR8NIuK21uaFYwdgreQ=,iv:IRYf+oHCzzbxoravdGZp4vGv3nfdJzRrykbeGCReYeM=,tag:4bBN01PzQ0+26T2h6YURRw==,type:str]
    pgp:
        - created_at: "2026-03-02T15:21:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3McSkAh3rFhAQ/8C7JUJCeN5d/hoxu9oxqjTa74cg3N7dN/2vq0oFYOVyTK
            fBC/3Hn8BE13WTgP1WDsZYiqQD8PNzHYeqA3nCbLinDbEyCRdPq9s89JqktRDSCi
            mMbl/CJXZstcA1i5yoiFGDPmn7ylK2sJ69bPu4/iM3sQdVu6CtJX1holDmllLTQ3
            CaClj9nUE66KI0OhpMEFKV3F/4XRdo+F/FQV/mvBBJjfg5fFhF0rBZfeDIqu2OZ8
            G3Vcguo6HNnwgO4deSVvxFQ5g3gD/Yyg/4rgF3Vg5bW38oRh3lp8JSNH/08wuegi
            1inbv2nSZSTVIaZVHdfAJn82CmTRhBRPStR6nnvv/0gwcXIPlzskiH/Ys1qOfFNH
            t8HSuazdgFp5Cf9vfaI+pl6GKLmPT46avpMwwOZdKqkfi+dRsPz6xcPg0Sd9ziLm
            1me37i46j6HgtIep6mzF0gAUsa8H28ZmRg+o2aM0P6fb691UUL8Eu3j5r15fFXen
            GiaUslQsV9EIqURkqJl7qrscKzejQGavPqibv9LilxWiLr+HD0ix8ID6ZIGNKmEj
            ivJbX8v166bXY+Jjk18rNjZCVm93M2/h75sg7d1X5JGkhpcjY5lqbi9DjG272KJS
            kn5A8ZZYAB3nqc48h70Hdqy1WGm3HySNSClVmn+PrJCo3TUJuh0bio7rVeYba5zU
            aAEJAhAh7V4xWuYOi/W6JueQaiDItBKhdygOGfFZLfWnsBxHdJnZ50D9SM4s0nhu
            d8NL0DGNQTLl03WMikeGiEgkZ3Di8CuhzLH62PEM2UH2FpA7onh6WiowSEOyAUMe
            Tq+jl61gCwXg
            =UCHL
            -----END PGP MESSAGE-----
          fp: EF552EBA773641B396D26658E1F56350C447581E
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
