apiVersion: v1
kind: ConfigMap
metadata:
    name: environment-secrets
    namespace: flux-system
    annotations:
        kustomize.toolkit.fluxcd.io/ssa: merge
data:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:A7ALI9+YzA3JVV2TV+sXrWNDuKA+Ji4KdFVNmqupL5igiQB6mETwRw==,iv:wNLhUiHLbw5RuR0IAxfm/gfcQohenk09c15JDYuE/yc=,tag:BgfZkyF+SmBcr2c0eZEwfQ==,type:str]
    VALKEY_PASSWORD: ENC[AES256_GCM,data:kuzi2m/i+zm3SqOfazi0GRsjEJ+AsPaW59TeSSfq2c2vj4Kk4bqZesSMEA==,iv:0czs3CQi1NOB6y3O6qDK+oPoHKdyIM5fuWXtd9tKM5Q=,tag:Ok2t9xu0D+AizPF3jKTd+w==,type:str]
    KIALI_SIGNING_KEY: ENC[AES256_GCM,data:LzoQ/M/DJQis6VCmQe6y9nCpSKU6kMaZTvLghCXSG2umAxTSdSyzFYFlJQ==,iv:3GYu5jOHns+2VhYtfjGM4NBeoWloLED9TPb5eLVAyms=,tag:wAPqFb0RS7/+3R33BtkLJA==,type:str]
    #ENC[AES256_GCM,data:qtFV7zhEILNzgA==,iv:AtnEClv48CtyJkWvJEc3vZq2/d1zu+6tbfEIDbgt/Sc=,tag:q8eBhaC61OTHsHY90BlrPg==,type:comment]
    DATABASE_USERNAME: ENC[AES256_GCM,data:z+en2kAkJrU=,iv:IWc53R/G++WtZEzuwaFOS83YyvAl8CAkHJML6SXwqTw=,tag:qDVr8wOMFdvpa1SY8kYFUA==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:NFyH1aw+f0yC9F5gxY6XkW10PuEsPKRyfscMu5SzcKxP13qcfFPsqzgzjA==,iv:uaRAPf/q0bScfT95wCuk9JanyjcHSox9x5Nmpe61QEU=,tag:lrUZn4ur2I1DWyIjka1IXA==,type:str]
    #ENC[AES256_GCM,data:WlCVLVe/HNtpKsd5Ncd5pLcr,iv:+0K4NaWCJX9aOS/FPYDX7L53VA6Nj0dVy/PGcZzCqgQ=,tag:daZXvV2yu82wxnWuaiH22w==,type:comment]
    CNPG_ACCESS_KEY_ID: ENC[AES256_GCM,data:u19lM7j1oO5nDApB+rIXvWzQ29U=,iv:WZnoLbmtn3MPL6cDVF7/zTA1xIAi5MWheWzArwQPrNc=,tag:Ou2LzUgyJt8kOYutTqz9cw==,type:str]
    CNPG_ACCESS_SECRET_KEY: ENC[AES256_GCM,data:RkIdlL5K3hCY6/CVzepBc9EAAPLVkS6oHMKdCH+gsJi4hp5Y85HaQg==,iv:hJqYBt4CKWEfihcaljuAOg/pouXktZ//zWsoLQQmoBc=,tag:FxFTxsbFt6q7Py2nTDKZVw==,type:str]
    #ENC[AES256_GCM,data:FSpBRChbJT8IFXUb,iv:l3r+bOq/eLPb52vr4rbCiuP8zngMYfdoc/w/JbcSiHM=,tag:rYzAU6vGDaDB9YRHK0KJTQ==,type:comment]
    LOKI_ACCESS_KEY_ID: ENC[AES256_GCM,data:gxRsL7G5cOOIjjS5jiamalH3nck=,iv:zEHRucjt+L/gBd1PwjiZx/mDqby+cAXNyX93S7mofbw=,tag:rw/qiaX/6AeEQrBDfK7kzA==,type:str]
    LOKI_ACCESS_SECRET_KEY: ENC[AES256_GCM,data:PibjOy0spgpf7NbcEYnJJgkf5ue8UimBZKz4hQwewwYumc+hLBBNnQ==,iv:ITpmwHrZlnICwJ2vWPOkkZrIZp5Z5pXbjCmSrlnnuXQ=,tag:FQq8faQXr2QC8CN66NYLIw==,type:str]
    #ENC[AES256_GCM,data:4JvQfnClxnVbHDqs+Q==,iv:ctVwIQqq7Ke1tEiHv5qibssxjiLu+yROBh4E7/MoOpw=,tag:/yzZymgvyQs3HDyp6E3+0w==,type:comment]
    TEMPO_S3_ACCESS_KEY: ENC[AES256_GCM,data:u2K8vPbpmyw8phxxhxTxDYjKLMw=,iv:1vxy1ENmoSRh7xCDzgoz1yal9b84bZqWgAEKX0KhdEs=,tag:00L/qn5/JkX2nyEgW/mHtw==,type:str]
    TEMPO_S3_SECRET_KEY: ENC[AES256_GCM,data:eOHR0PGPNyazRhXqxOxgjEQQ8Q5c/N+ic5cCNvF96iye53EAzatTHg==,iv:o0Es3/KLGo+MZ+UfDlsrZrE/TEOMVG0J0wZNV0kfNNg=,tag:lqJDTtcjPOUF69hbx1Qdbg==,type:str]
    #ENC[AES256_GCM,data:g1bKWJgW0j7Ds+v8sjA=,iv:QcoeCMhxYZ8PC7HgYb0MFNYDzJnFNyHBEyVHuYgIh+o=,tag:2c+O2DlYLdFNBaFo+8+CDA==,type:comment]
    THANOS_ACCESS_KEY_ID: ENC[AES256_GCM,data:XMOTdpF/oU9uJAkfOkuCzQYm+uo=,iv:V4D6GQcnyTc5EbI+X8bbCOxjP6A5cuvM2sMf7JDxfzs=,tag:UUsmhy04cdw4NdSL7ioE5Q==,type:str]
    THANOS_ACCESS_SECRET_KEY: ENC[AES256_GCM,data:cSPvf81mvzozViByX0HX+r98HtjmfzVnvvGkeC/ObKtcD4ABFTxqCQ==,iv:2mySUyrjTa37bL3ngmbYaFqbzDANQf81ILL88/Wtfvw=,tag:y/GHGuHb9LiOCO6OpHRa1A==,type:str]
    #ENC[AES256_GCM,data:h3Sa6h6sNl7zOiVs8zAK,iv:mEcww5s1MxbWkoz0l85mmWxGh5dGDvSFBBsacTKyb0U=,tag:+xzaAETBdXDw9rYQzlj7kQ==,type:comment]
    GRAFANA_ADMIN_USER: ENC[AES256_GCM,data:rcizzfg=,iv:4k+Olu80CD9sYiSr6z2YzvK7zv15vRw4Wr0AhPBBoz4=,tag:2jvzgVIikjQmrrjh6Nl/aA==,type:str]
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:kiproUZYSHoVSz7ZjS9+OidycocxsL8IRHF1ZjcW0krSta509U3S0UErPA==,iv:Qr9s04Y3VMPuVOgZ9lsnXalKPfhmKutQ3DGF2vEr3rE=,tag:jD4d6ecf4yYOaDd7rMwi+A==,type:str]
    GRAFANA_AUTH_CLIENT_ID: null
    GRAFANA_AUTH_CLIENT_SECRET: null
    #ENC[AES256_GCM,data:TyfEFZMDRrfjTmh7KRfI3+UP47TA0Ug=,iv:4S4suM3jV9SFIdcRNqb15UXOIJujbC9ifKrwvDQDUes=,tag:di2+l9nq7XFBrzJSwpd9Eg==,type:comment]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:G0UpPtJV6vf13mxxLWpacSodhvo4Mpvly0NgxfnlWnoQlKiOelvO9WwRGrRSVQ==,iv:Lgkv+aV6WSMuVsVTv7Gjazaya1K1ot+jnXupo4nKJcs=,tag:SwwEv/LKETP/v1O9SxpoPw==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:M/I0GfptWf/nhM8=,iv:LcduvObLqgT+jkUSPLYBNipr3KiAcdOxou4bv8sdsww=,tag:pkg+RMlyN6dlWPgnH8Y7GQ==,type:str]
sops:
    lastmodified: "2026-03-04T12:03:36Z"
    mac: ENC[AES256_GCM,data:LWQXgQUz5bHp8M1KUDxqccOcje/zUdepioIPgv9TMNVExSXbwzYKiJZN3TKsr7kuabO8Eetq++riVUyd31pFh6XT1VKWrEvpgYmHvKdURtnAPEVkj+eP7wn/Xw5oE/VX02FA2UoFhV4MvgkSogGqf4SnPclMpuX6k9aUparN1+Y=,iv:QYkpgFpfhC/qu85K+d5xdDSsvxQGEUTWraXAVakYbcI=,tag:fuYyi3C/tnuu4x/EvIQ9NA==,type:str]
    pgp:
        - created_at: "2026-03-04T12:03:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3McSkAh3rFhAQ/8CVS3qBDdLTSZwsv72LRGDBs8mjtHQWvL78L9xCVfwow4
            SZ7Lb8gcfcVMaNhOqWILbuoOnCTxL9fwfRhDY6+WE0J/ImnDuVckW5ltw+N6z12F
            YjyRCQhYT/Osf9JORd1lIUp0vx3H1y4CShq6zOXCf0aEE7EBaiw6ArFJgMc37Pu+
            mlDO/ezcaeAv1ODu82l/2CfSGP9sERXuQUbsxCYRw1D6MIfSoRr41y5AYQL3/WsD
            jodnJv3+yWxGwSgt0E+uyfEB/Eq/zTHGWH8crCt2R4Kge0VH6mcljSTv9Ovw++oB
            +wbhTPTEogadCO4KJeTnjyxET7cgAylDLCWkhRxjVBai5HoCAVEyXOhJNaGfBmqQ
            jTpasocVp+YvRpZQN8CTN8Dvk60BsBOUr+Wn7j1FlovBxangdlwToyBbRXZmAjTG
            fjEJZ40GqpJOseoUEUTulF7VS85UH3gYA4tl43n2XgmV3yfbZiT60qyTabLtJ18z
            e2pUktkQWcS7pqELhYbrvZtGRc/owWxatvh3bjsMkRroa1Rin15D9sr/zhF9zm7v
            vzBIOa4K1Eq4Ur0+5UklSaQtTav6kNaYZtFXZiRU5uenZRGBcPz0yMXXPkRXAkg4
            DJ9K9tZzav2ungxqt+E3JwJWF1Ja15mPf4wTGnCdWMu7+AoohJOszJs1VBhav9/U
            aAEJAhDgtDEZKVRk4tgexcNvO5zBlX5YDjhnhfQpBw0BtKTLQCmwskqpvD4e7FVD
            s3JKpW+1byEEcTW11sgLtwjEX6lQVAAZZATksOXqRjuhronriaU7id6oBAQm14Je
            A0QeL9jHvo5p
            =qTKx
            -----END PGP MESSAGE-----
          fp: EF552EBA773641B396D26658E1F56350C447581E
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
