apiVersion: v1
kind: Secret
metadata:
    name: onecloud-user
    namespace: cnpg
    annotations:
        kustomize.toolkit.fluxcd.io/ssa: merge
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:OQE/7rEONgh8CShyI8ef09hQwOA=,iv:qvUXojq11vSvAYUJciu8Wueak8kpdqhu1XSupKTezTk=,tag:RnKeS9ksvEqKXo4ehuFUFw==,type:str]
    password: ENC[AES256_GCM,data:PPfAE5K/YHGWfZl0Ma8YuhM1n2Q=,iv:/hZbACRiK3Y+xXe6EglQFKfxp1Srq2pz8zkukdlbPHg=,tag:ersBiKAsX+k3Pxd0WOV8ug==,type:str]
sops:
    lastmodified: "2026-03-02T10:19:11Z"
    mac: ENC[AES256_GCM,data:DxMR7/VPDTJtaZpDFysFwRAdGSlNVW1gECS8vdftSj1NKLeY+HoKiDoI11O24buemLMkdjdLWZjkkPhPQH9kPGxqCLAb5oGu6lj0zAAIjsn7KAKWlH8uuWilox44P8ApbDlcZufUAROHWLXLaW2z2FA/XnlsKea7m34WGanWOFY=,iv:6vKkkADEnyoeWfnZJOBeRCaFvTyOH13NIqL4/VuJyqM=,tag:Boz7ooApBYjchY9fAsN/0A==,type:str]
    pgp:
        - created_at: "2026-03-02T10:19:11Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3McSkAh3rFhAQ//XffBt1IgEwHtgbUW2fotOUeLx1h0R/nrsXxaxgB1p+5H
            uArkhIHIIsIyJ8Nc8ZPsyZ+c+zGCwZSSXQXuwlA9EaA6NjXuFJlGaLCw0FDPozOL
            9ZC/l8l6riXSBj2DCmlJHojLurVa8ZiW4zpV+3beV9wE7VZjrpZ4O6UsFq7M2eJf
            GGtfYzRkzY7qpZ0rI0WFBGoK4Z5zNEsWvj3eF5F3nSS+W+6fRK2+oAxcO01m740a
            OK/ynOEXZ6Ie6918sP0IET+wcjbTrsue7CAwO2bf4L/Jz5UmEepsZGnFuhB0kfmn
            vNbSJoZEja3CJOo0qrl4e/JzVeB++uv4rpzLoySXaCcORdEcxapO638yQdWELIi4
            hp4Uy4WFuWYtUyZEcRqgjn01NTdZr1EBoOEsv7KMvRXHicubudY2aXX99QT0Jizq
            5DAPUSS6a8eJ0y6RWdNDkF4flmx1mYkPLgQ2RD2c1s74F68+fnv9maYRJR5IEPoE
            xDBp75fldi0vzbUb7C3w05LApG3MGBolwIUIzcljqoqwiYCA6w3Tdv2TEMSWvbdl
            brELtNchzHEjo7bRiEP5r+MpzXNy6SDSxuf2P85KQMoDhVin84Y1NUga1Mp9/3kF
            Apm05ubIe8eOmklOt4Gawe2C0MSHGBTpjSCdo+gXH/CKhiGDfCVIZ09MSUUYbf7U
            aAEJAhCTuV8A1n1WkFkDLzZohUVpGu4mBRFqyS4HiXxkhzmrOeBGpRgaGcuN3+kp
            IpPrpssZeufi/J/yw+TKWU0PyytPhUZh+9J8yr8tNxe1qZbhMwSIrxGmyh/NActr
            UD+btoMMXEPt
            =KfTe
            -----END PGP MESSAGE-----
          fp: EF552EBA773641B396D26658E1F56350C447581E
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
