apiVersion: v1
kind: Secret
metadata:
    name: onecloud-user
    namespace: cnpg
    annotations:
        kustomize.toolkit.fluxcd.io/ssa: merge
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:JFN3eJEz018=,iv:Cv8OqSXXvmirnGRJMlMpib1uwBaTlSwXo95nkXUnyG0=,tag:tcJ8xsxZX+2uHYsCVkRI8w==,type:str]
    password: ENC[AES256_GCM,data:9S3GXUqVC0oDljeUyYiWgw==,iv:K0GwzPOqESpGmBYOf6d/3TFYDTF3O7QxmYX+459m+bc=,tag:AsQ/Zn/ZRx/SGQxfikmZZw==,type:str]
sops:
    lastmodified: "2026-01-13T14:56:31Z"
    mac: ENC[AES256_GCM,data:GzbRFSBrfp4TPS13s24yUC9VtttVN1N24aabOqRjO/BN+bgu3tFTVHuSvSS0QEpDghLhmtN35gmqOQ5LUGux4j0MXV2xYtdCBsH5Gk2BpdHPPAaiOWa1ODwBinmTs3NdT6MEpCsliKURSEeoJzEuzwhldZJHpR+ESZqPUhcPdrI=,iv:28iNOATUaajJWOFoRIV5bOzcDPB425pY3xgjinTG01Q=,tag:Ta8hTVD7SWdcGRKG8R6UMQ==,type:str]
    pgp:
        - created_at: "2026-01-13T14:56:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3McSkAh3rFhARAAg8rUws8Cxy7lWElRvgfRe0sCQf9M1wTdwLsgDs0hjDXh
            jfdRuOM6JZQyL8U+jTxN/5Dv1IesLygMiA+uEbqA75cKTxQgCzxo2M+0+Df1o1uC
            UE/BigAfu40yVrPhiBG44l9lZz/qFLn8QgTLjcaY2Fzi2gl+/stouxYsLk8mcAlJ
            i9avye1UlO4D+gcP15cHl+EcCHqKo4ifTiBoXizZ2/Ivpd7enesvPoHPSng5Ti8R
            B2sXXeZLQFZesU7eGLyuDGuugKbWAGWjundJ1HqW2QifBq9fKw0ovNhIGLaAtF9w
            3XFxRRjlLXJ9qZPluKBdN6hKltxuS37c3JQz8qqLanWK2bQBPd47V9zS9slbOCMh
            NjdAEzopPOjaIgq/sGMd8F6WbZ1BaVjDg9MyEBKYDlR1qBeBlYCp/ZjqH3gEtsc1
            AbnUwQbGCDfX45Mx3bgw72EAVK3plFnEXmRIm/K1kxyoRc0Rt+r7D+F9ur3V4Q8w
            ofr6vXS5VynJ40hBrQLrs6sUaACsvjUV7i6BKWtKfRBVS+ZYAPLBbcQYf5gNDBp4
            aeNF8rrfuWqJeZwqpVUGai13qtrY3nT7RhzedZXFcmRpbiArVrGNu59PUtioPelH
            qHoRXdc2p9s+JzbU5LkwzR7ruYKUPJwxdaq1VZ08FHevXyO7ZNtatp6HIwpr2M3U
            aAEJAhChClb/0J55j75lDf1UCFkqphB3NEZ706JQ9SU6nHSPZewBqPBgHh9/DU8P
            15psvE4jZmuzRLagUjoR1fw6psCBYdHQ+hzdayNr3XHBEebQU8HDCeIUSsWO3lAg
            yzM71Akvpb8w
            =0YIl
            -----END PGP MESSAGE-----
          fp: EF552EBA773641B396D26658E1F56350C447581E
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
