apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: istio-ingress
spec:
  dnsNames:
    - "*.${HOST}"
    - "${HOST}"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-${ENVIRONMENT}
  secretName: ingress-cert