apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valkey
spec:
  releaseName: valkey
  chartRef:
    kind: OCIRepository
    name: valkey
    namespace: valkey
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: valkey-values
