apiVersion: v1
kind: Secret
metadata:
    name: kube-manager-secrets
    namespace: flux-system
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:rH9amVhwLMrsfXMAtSO2B8RuaKIof2DKwVvQthzOkoc8rX81G0lVKEPZO61sOP3OwVMMgDXe0KMkew/10lrBMhiufZMBofLtrNWpBJKR6GGjv+FIoppuyhP9ky1Zv6Ylp7yHNI+tN9y8QRFOCe7Y+Luk5jrxYeCnznhlCdByERIa6RJDk4qLszbJ8xaLl7cvdcjkKDs4y4rpl73jzVI29XvEpsFB5XrbeJj18CXqzo+bKoaCS8D4bTWpkKEMkemIo9Cp/Ztd0C+1UQNQyEzE8yXJUXNUXcMwgpBrh7uRuOtjR/vCoS/wFWu1pfzIlFh4b61FRYiqkQ1xq+8lYJ3tNxVptrnfVGhDhpBaCLPhPnre+CF8Z0tUY58uIMhsbrO3XVearnhghZM4dJSD4ZEOrKQQr0eZBTPwTJMuNUqtlQsHZlrKqWRZJj5vx1xOQfw5LXkcUiNwiamcDWQ8nSUqT50fhVPbTHi1KqkL2JRIfwsaFmLVayCUCHZZ6JR3Xw==,iv:ElQCF6POycRTbPMt2MnFa9TbQo/YkChslpH8pHa+dhc=,tag:61AI+Uh1+ys50qOEAKVNVQ==,type:str]
sops:
    lastmodified: "2026-03-02T10:09:00Z"
    mac: ENC[AES256_GCM,data:M7460yEV0Usvq1Oos/aAKDwiDGHc+q+cdaAb4AHfxBD29Tbb6WNoy+rsJxhVu1gGLjjRIKemXDfjHiLhgItv1GbfKzzn/v7/4/aL0C43BC2Ib7DsF5dlJbz73pR6qg9sMB0q3gOdja3KK68OQUheG4mYjOOtcKW5Dgs57j9m/64=,iv:LniqwxHcMl766zmBnlfLKG/o+ClrWQDmMp8zWqHQR8E=,tag:mVHYNv+EuXzfXR7oVjBjIA==,type:str]
    pgp:
        - created_at: "2026-03-02T10:09:00Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3McSkAh3rFhARAAgIRbbxrD0RbUQFO8LwmEy0VvKfQE5KlChEy4e59+DTsN
            MgeRRdr8I+KU4Ur6Fi/wmD5gKmIXGzW+e1UTCTUlB1lWsNb8dnOvE9/1jmmxu3QM
            rjVmSaw0gol02GpOP5MhMLthMo4947LXG5qY/M8kI82WwBFWptg/ZkiHr6CYrrox
            781hU3Hoa7p1D3wHucemIHSrYosMzXQ1Lnr7fozWuWqBM/RSywj1RvbCAPF1Z5jX
            lmLotDjK9XeEXk+lia95ZSTE0Lkl4sXYPAeTF9wdRZZCOs+4zV+6lJ+tuDHDGFy7
            PRLdY3n8Dto183SMYz71k96PbOD24KfGuVhOxTKWCRns3mWPbUtIZXJ4V7pponq8
            CU7xgjWyEQXRWfbSPJvbr170ju867XeikIEGkWttNVgrpbj3m4k7YKxMWOH9K/3C
            rBRg6PEobm3+PQv8jaEQ8mClYky+7EN66jwqXDqJ9Jt9l57fhHiRohEF8qaiytxb
            N2FucVLN5NBWQ/KZYTuYb9BLaCkoWPPdOQ7jWz3HSiq3506S2xdNboDr80koaYS8
            m/5Xe+bBURLCZ9HZOCsVx6EmaEoa3yczCzAQJN45NMA0X+X8Z08auGAQjLlr6X5u
            dsS6cirRPwdBMBGgSpxpf29K1x0J6uNO6ZsHPFUDSKFoAFJZbbEmsxHs8crOf7HU
            ZgEJAhDPdc6mxiWwzpWMYrrEbX/NUN8me0nu4G+W40jSrlHR0eTqaM2OqUD9SXb/
            Cav4hb/YcWUXYRPkVAs9GfgXaMg/Xh6Kd3FQZo9ZypMSVLEluCmZRULfJ2j2A0Zz
            j8Yb67XyZQ==
            =5p18
            -----END PGP MESSAGE-----
          fp: EF552EBA773641B396D26658E1F56350C447581E
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
