apiVersion: v1
kind: Secret
metadata:
    name: kube-manager-secrets
    namespace: flux-system
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:WyKhHNYievkVoNwk5rbDbc4hswMo7ln06vjrwXMdeZvvTrcctNXEDXRCfMqSdPV+UkodjgFxPttL1cz0saqNEZy57Sg5H8ecrM5lUkycXQ/+Z3aHPQ8QkIpegt+PdFP5GRzghMfmGb3M2HE+gLtK/QU7Hb6OGlA2j1JntuA4z7M9pXTWFpDCojWFBkyrC9Evva63OSSjL7cuCotA7P+NPqxPxkcw1UqncpYehpS1lvFQxxyRLBcj4661JCcDw/+PoF6AF0lJF/CBCcCJwq2rSl1XgeqtI9l2PRo8M0OTDE92moBo89MTPjdFo9MdEzKBhF3H3eyHyPABXwerDYSPiexINHOip0TyeGoeZPdVCNLK/4bebo0+WAV7/xq6uO6DFkHs3gbgqTMNmR4hVPbw7RzpNMNFnZT8MeuSjFfonJr8vMjkkrkcRELFHB1ULnPTV2xCrUWfRZ29O9I0rwQJLO0MrrGPX3T/Iwds3Erzj6KqLyLSeCZ3tkxObYAkQagd2IX7TphN4tCcE1P986HSHJd2c7q/IGenJJZtIdjyKCcByLSGLHwMa/AbEiSsYy25ryY7RcaZ3x1HTe9QNOTwIIFd+3VZg9Kzb/saP4SnMY61YXjBAYSjiU0OkLEVUd5RxYoiwUqc6g==,iv:aoz6ce4CX/HcdcyoZm2s4SXm6yzGABf9wkkytTI+o1E=,tag:JE1V9Cfa6iXGcUk+ucfHpQ==,type:str]
sops:
    lastmodified: "2026-03-04T12:03:13Z"
    mac: ENC[AES256_GCM,data:Pu11NYB80wSeqq1RRjoAIwhoJaWEf6C8s8AzpnT28cVIRKcEJr6KOaKnxrMjhgNbAsoEryOwS6bRZcX9bavxgGHyIf+m4xgxCa62HFnvS93sMY943eamj5hidESLAv/x/uUo2XpA1yZA2x4W6nGbclBkpEShneNDlU7Ct02m9tg=,iv:IRmXgrr/GJ4K0n6bqy1NQzaHC58r1AcpithoQodNszs=,tag:c3delqGi5+Gh4/ij1QztEQ==,type:str]
    pgp:
        - created_at: "2026-03-04T12:03:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3McSkAh3rFhAQ/8D68ej8BJA0MUOSKsVAF4s9SWcxCelERlCHuCpp7URm8j
            8LMc/GIVp0n14P7plfaxZ8B3n1vHhqzG/sW6XgpxG9YzFePh4P7UemUTCWMczgLX
            ZoBCTJ9NsjST28GusQASz00Fvndrs4ecvJ8mExS1XL9kgdN99ULpgxewfQrgW1He
            sLY/+9ACIEmjJRh6Q3Rvb+zgdipzX77Fuz8Yy5doVXyxAdd41P1kJ5JYGMFJxFQ2
            nh+XQdzuMxY/W0EgjgJXI3jTZRhI7bVCMzT7auwPC43YD16ibzeQ/3ER8gt5swhz
            Tfv5Di21siLkeuSk/qDsyJrR+JyIG8uOeGhCR7CQGFBIZi7ayUecMPdsI6znFmbz
            kpa02ijKw0UAhzbWjr/unrJbG48q5LbqyKGdOSmiPsw3fVLeD+P+Z5hOiZiXuQb9
            CbgoAKWyRO2RJe+pk9QNRbAy6n61gynfsdvgtuSWNtj40ImiW3qX2RZ39WgySpPv
            FIo2DS9xkKsDe14L9UaiQL223FWgrcMruOZoxstnIAEFENxHceocr1bGUwKtAbFO
            D1Ry8SY+Zqib9PtDXOk3U+HS+qrZcHJSqduShI16574zZLKOdzmFKQH7D3Uw9exC
            yhr8mAFnu+hIDULLFd/WcYNl3Fx0YE1273YPdQWONFTzSgRKKR1ATfuF04f6uu/U
            aAEJAhB8tQtxn05UrgzAG17kHgH5ze63D5VLCs361F7RTQ5LBX42yR1gtp/2ENu/
            X7BW0cum3ZIQzysneM7hIdufPXf7AJ/nm7zmIZH1p2ZoH04PKUb7eBUvYLSv4+8g
            ML5EGNK56ski
            =qECe
            -----END PGP MESSAGE-----
          fp: EF552EBA773641B396D26658E1F56350C447581E
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
