apiVersion: v1
kind: Secret
metadata:
    name: kube-manager-secrets
    namespace: flux-system
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:OrNgnyVpwZx7LV6fXj+ZcI5ZcDvlp4Iyr6iC9lf7RpjIKzhgv9XLyDJAuE3zeBa24tACqv45bC3MNueMDkutmbxobec5qcOVJPvs84SmTg+FGkBGDME0j6CgvYitqjqFnt24g7zYr5PkUvdzOIWGj+Id30Lf0H/5g8L9YlN8vSYWM2S/fN/xEpnTCzJYutEQtm+i063auHHPyrE39874ykZkDZ/baT5UHH/KJCc43y7yMkWf52cHVSsxPK47VPad8m16msTpWpojLUfABcWeSiz2EJ9wokT+g2tYRVceVT78aNbsXZY/ohO8SQD+dyjc6rzktJGHZoFRSurOosWA8V6D3L02Q36I8UiLOb1s097EqdyOZNbfBI/9xFxymhYlbB0G0rIlulJpUrwtGJTck2coxyrLG3OKctYhLDXH08oZTeScrhk/SFUfkxtWPVFtgmAdYV2gIwUAqkQK51L8p3dhAmBfSQwuvtIwZO12FwgnN7QQCSiHzCxipc0+ACYYb7/C6Sl7A1ner4tUVGMjjQp9asQ1vkLlZZMGIjdNFAyqgDCSpW25Ml7oq92TyY/iqSRC17C3XlIr2Ob8piDXmGHk/rNeRpQwBMH3cpP4I9vyDFMNzaTwqaMcHZ6HhPxv0/qYiQ57/+DKNzm6Ww==,iv:5db+svquyTgPuzPZGLlB/5zea6NOepNqqwtpzM1an9I=,tag:MU8jMIbdGnX6VHsFFMu2+Q==,type:str]
sops:
    lastmodified: "2026-05-19T13:43:28Z"
    mac: ENC[AES256_GCM,data:+6aZso/tbw3nZzTKD1OofgDh0u60FIQO472M9lUpz8IDmIFNJQaSxqKyD7IubvxZVE98n3f1Q4FQkbnd8jdq1JRvl8+P88GAUXlmxoyE53M5IrGdE9EwiFI2Vr5D+OgmgGWZrXcO87BB0TeBObbeY2YbdCItnoEIxdDSP9F70Ps=,iv:rF5rkqe7w3yyqRSkO43LEee/cdv0P6r0IFJKEETm4qk=,tag:AVl6cqEDpvo6oLTp9/2RFQ==,type:str]
    pgp:
        - created_at: "2026-05-19T13:43:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3McSkAh3rFhARAAgxzlAEycD3+YBfLiqmo4KEQCOCzI5xNr2tQvQvf63nGL
            DVKsXcO6vcry/00taboL0maUxr3gy64xjVlNdFiO0BJ/TNN7IF2AWtRbOrMBqp4A
            jMZ5+QPhaoCN7Rl1TASoQCqxTqUKZcF8/wtBlcFv0cP22rrCEU0nOo05hK8u+RGs
            QdzrXS7wDzO8ORUUEENH+drh971DosbX2q4GsoiJjRQQL1blDyUEx2z8YWeAeCE2
            f/cBrGlfP7OmEj7hXLHMda73ld4CROm+eP5ns6gPQKSrkC4DMaqGyubv75WD0WZ0
            +N6/sqrwy23gbUsEtjZ/AzEzyRp8jqAsdCqnvs/bakdYEnwbeWLuPFOeahOInAvP
            DIpHTNL0VnCHt+PT2kLmng8r7NZHyIT3cgkoGp+31bgXNxsz99dpeUaBmJixw9BU
            nk0l0RaFS6kVRH9g98S4BUHdP7s7W5NXr5Zh7mCs8dpfKoTjvi5KRTPxWEZ3J8D/
            18Q9l9XlD3Qme7KZf4gkwkmQ2uBd/vKge8OvD/bzAbfvkNNptZrth+6w6spZjW2A
            DzwyUtXts5wF9ozIddnTHAfdvYGmgm8VXhPd5SCwd1GMBTw1fsxAgw2EcClia6VK
            niZZr5XnrPlDijOJTYvu4o5iaM1R/s1GI+smgjSaw34p66sVx93BxKzsTbjaDQPU
            ZgEJAhA1yVKNxvHlwfdjPode6Un2QgTQnj7rFFEabZBo91MPMxFUZRs8QvTqtShd
            /g3d4iKg3jIdLi8E8Hyayzaj/x2Y21NwyWX0BkCRfDm91CJ+GutpgAtkSYOQBsKJ
            CvhOFrJOZg==
            =4O3H
            -----END PGP MESSAGE-----
          fp: EF552EBA773641B396D26658E1F56350C447581E
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
