application:
  debug: "0"
  allowedHosts: "${HOST}"
  allowedFrontends: "https://${HOST}"
  logLevel: "DEBUG"
  region: "${REGION}"

database:
  host: "postgres-rw.cnpg.svc.cluster.local"
  port: "5432"
  name: "kube-manager"

redis:
  host: "valkey-primary.valkey.svc.cluster.local"
  port: "6379"

openstack:
  authUrl: "${OPENSTACK_AUTH_URL}"
  domain: "${OPENSTACK_DOMAIN}"
  region: "${OPENSTACK_REGION}"
  externalNetwork: "${OPENSTACK_EXTERNAL_NETWORK}"
  externalSubnet: "${OPENSTACK_EXTERNAL_SUBNET}"
  adminProject: "${OPENSTACK_ADMIN_PROJECT}"
  outputIp: "${OUTPUT_IP}"

telegram:
  enabled: "1"
  groupId: "${TELEGRAM_CHAT_ID}"

openTelemetry:
  enabled: "1"
  endpoint: "http://otel-collector-collector.observability:4317"
  serviceName: "kube-manager"
