---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  releaseName: loki
  chart:
    spec:
      chart: loki
      version: 6.29.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: loki
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: loki-values
