apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
spec:
  releaseName: cnpg
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.23.2
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: cnpg
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: cnpg-values
