apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
spec:
  releaseName: external-dns
  chartRef:
    kind: OCIRepository
    name: external-dns
    namespace: external-dns
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: external-dns-values
