apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - podmonitors.yaml
  - istio-monitors.yaml
  - prometheus-stack
  - jaeger
  - kiali
  - opentelemetry-operator
  - loki
  - alloy
  - thanos
  - tempo
