apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-configs
  namespace: flux-system
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: merge
data:
  REGION: "nl"
  DOMAIN: "ocplanet.cloud"
  PROJECT: "kube-manager"
  ENVIRONMENT: "kube-nl"
  HOST: "k8s-nl.ocplanet.cloud"
  EMAIL_DOMAIN: "info@onecloudplanet.com"
  CLOUDFLARE_EMAIL: "info@onecloudplanet.com"
  ISTIO_VERSION: "1.24.2"
  OUTPUT_IP: "91.211.89.170"
  # ── OpenStack
  OPENSTACK_AUTH_URL: "https://pub.eu-west-1.ocplanet.cloud:5000/v3"
  OPENSTACK_DOMAIN: "default"
  OPENSTACK_REGION: "eu-west-1"
  OPENSTACK_EXTERNAL_NETWORK: "76d208ac-ba1f-44df-a4a4-2789be70e139"
  OPENSTACK_EXTERNAL_SUBNET: "f0467537-9538-4155-a35f-12cdf79a9566"
  OPENSTACK_ADMIN_PROJECT: "admin"
  # ── DB backups
  CNPG_BUCKET: "k8s-nl-backup"
  CNPG_ENDPOINTURL: "https://s3.ua-central-1.ocplanet.cloud"
  # ── Loki
  LOKI_BUCKET: "k8s-nl-metrics"
  LOKI_ENDPOINT: "s3.ua-central-1.ocplanet.cloud"
  # ── Tempo
  TEMPO_S3_BUCKET: "k8s-nl-metrics"
  TEMPO_S3_ENDPOINT: "s3.ua-central-1.ocplanet.cloud"
  # ── Thanos
  THANOS_BUCKET: "k8s-nl-metrics"
  THANOS_ENDPOINT: "s3.ua-central-1.ocplanet.cloud"
