apiVersion: v1
kind: ConfigMap
metadata:
    name: environment-secrets
    namespace: flux-system
    annotations:
        kustomize.toolkit.fluxcd.io/ssa: merge
data:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:vEaBjfvijin7/0/8TzDzorsDlfQHn5bzKjZbedsrLwuiXXAgR9ktMA==,iv:JTugDh9I60w6ka1MzyYl7Mg84pyRbMvXgVjQD5tIO2Y=,tag:4o8F1FPcHYM0BmgLqKFUlw==,type:str]
    VALKEY_PASSWORD: ENC[AES256_GCM,data:SC286JL3cmCYPB+p4iK9VGZz6dMjRrIpK36nGfI4myxcramyueoNkFc0,iv:o3iVRvfpEK6quVtSRY7MqfzzVzDWXhRJrF38kIsDap8=,tag:L7ue9n87oc7L2NZN5hNFcA==,type:str]
    GRAFANA_ADMIN_USER: ENC[AES256_GCM,data:WsO0Pyg=,iv:qmEyE+1OwEmf+3eWfKcN8Wtd4Yh9mMqIIpljVSv2Emw=,tag:80vZ/BWhP8n6U9kTX51eLA==,type:str]
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:9SHx/hJamKY5U1kNYKJZADuBCdEtPfqv/zakuE0sp91zsX3T9DezJaah+Q==,iv:cBogC4SlEQWNvFWeLhWhSKP+geQijGiWkM47YBMXlHI=,tag:9myvDfsIygj1rVhUyVaqtA==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:709aOKwE8NPlRxG48XaiekE/Qqy2t9HK1IxDU5WztDXS13BkoCrgpzDuNqSTSQ==,iv:zrM81kkE5ZRW13sHR0yHt9VyryQq0swsZRFy2SRsAv4=,tag:G4b1ZD7ImjzrI8e5zrm/DQ==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:feBSWQse0aPcjZY=,iv:OcOOdRDGrJf7rjE/qJuY77+E3bjECCqAi8h48mjClxI=,tag:emCBSX7xy1WpyEP1aA1CAg==,type:str]
    KIALI_SIGNING_KEY: ENC[AES256_GCM,data:RhQ44gUji32mpHTinXby9f29m2jTsiUTcfaPffPaUqpt3uocpboARdhenomJHTqukKUIjZEGS4ism9HbBBTYAw==,iv:qx6Z/wLcYgrrU9MYYoYpADEtyzWs5mKnhqZI8clhqZ8=,tag:/29O1lPs9J52V5L2mO5Xfw==,type:str]
    CNPG_ACCESS_KEY_ID: ENC[AES256_GCM,data:EnerMWUkVWEH+pBJQske9uNN2uc=,iv:br59ABS32Gsf4QADMjvy+DSiN2UkMJk42sJtTRN2K28=,tag:YRuc4fKEec9UEvg084eEQA==,type:str]
    CNPG_ACCESS_SECRET_KEY: ENC[AES256_GCM,data:+f46xNbvTfKChzWF9KDHOBETzWVZ6/ghKpngU5uokGD2JhkaDYZmkw==,iv:m54pGkp4pv3f7Lh1rctGvi6Cmru3UG+nIXY8Ip6ii8E=,tag:h6uvnt0d1R8mNb2P9u9ZjQ==,type:str]
    DATABASE_USERNAME: ENC[AES256_GCM,data:lGMe+x9rv5I=,iv:XDE7WJNvosS94tD0kkNfjL+0HS+2zEAZNO1dTiqJDkk=,tag:r6Qy+3QamvQuRner8gC3dQ==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:uymhhj/0zsMZnFXyiLQkLBXKXyBFmdr00spwnr5PGzW8IgxSU3ktfsxC/w==,iv:xrZztq3XRnGVRRO1PV+hi6hU1qRvsXqHS7cYX+0zEwM=,tag:u7OXVjCKiFcyZl/JB708Nw==,type:str]
sops:
    lastmodified: "2026-03-02T14:40:13Z"
    mac: ENC[AES256_GCM,data:6A6r9BRQNp19arbLbab6v+0elapuxW6gsfT66FPGgKIv/+a89/QA4IUCdaarvkAi7ccI9ZWD+ylnE5uJHtvvTO9UAB9Ik85WpzyZtYWbgsdmuxYv9r81xpX3XwFG8vJRhgWH62NFtMsuIHGT7IvGh7ZUIvUzXpfgxiXRcgf9FVI=,iv:lK0nqCN39Vkasr9UvoGDakiyM07nF7YCSndfcJMAmnE=,tag:B+Tvs0kXONyyBSQ549pPbA==,type:str]
    pgp:
        - created_at: "2026-03-02T14:40:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3McSkAh3rFhARAAgUnj/lIbmdcspPSJSa7xuRE7N24UxPRBtoPryqwZnx/U
            9c52bToyPd9EcgcCALtAkPKM8PMPJEyE203znDhVrb+t74PFc7rNzfXBZPGfzFqa
            TtllhyCIs1k5hLRako+pBBp5yPvOC/6C/AV87JLZ9aL5milj9Mafv0nd1T4kFy0c
            HEZGEapLCj4DeFJACqsQw1SQ0Dxfe2lVCdzCCZ67Acv3vG65fpeMmML3B5GxZRzc
            rVuutYStSRq98LV0ViOnDjRBe/k9GwQ+yn/AsGNacso1ZlpbGVbHNj1v51yR4yKZ
            PPZolAyqfGfolwkRwuxcVE9/q7IEJh+5Jbxaay712qL65Cp2KgtV0ZhzT6Z4x8tI
            rvtA4aOzXEJr2uLZKwPf0OGMhFULk2mdAZOwKDe4G4m+ExhURGnNLaz4yzDOBPpC
            oQy6sws+f6y9tESHUVEQYeffCsxTdT0NG4o7fLpGI4N581dG8M3ovo8mcqTkOroW
            kyDhFmvZfPZKKdCOadUeT6OXMoBkFqbgf5Ftnl2qcwgLRAd+vQYypBXbXl8IiS+b
            v4cBkoesYUVgpc+qrjiZB+XfKpO8FFtw/Xh8j2bawyZSUqO7q6/Gn+R4EhjvIFxk
            FN02/ReOTHl7oELbK2XJNSwW87fP4Xbdx6y0nhTHKPRpu1br8sq6nFXS+WUj1wfU
            aAEJAhDTW7l5PMFRzA7lgMy8uowAqbJSKSjLWd82KV2yfnH4jT0BLuEaeB5iEhA7
            1eYLcSGOzDPlYU9/Wc9oDVqAY+40j5RhkFKTJp2N0IjESLvt6bRDM9h8jk61nQOG
            asGjr8JJiWYD
            =x9qG
            -----END PGP MESSAGE-----
          fp: EF552EBA773641B396D26658E1F56350C447581E
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
