apiVersion: v1
kind: ConfigMap
metadata:
    name: environment-secrets
    namespace: flux-system
    annotations:
        kustomize.toolkit.fluxcd.io/ssa: merge
data:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:ODMTWnKDdZBQNupDIAZ8QmzOl7Pv89zzl3E9j3C6PD+jXwi5LmM5Hg==,iv:PSevenuVSauJAsQYoZwsUC4DgJJWgF+1gP39Ec7CIDU=,tag:L8a5RLpKmrtsgQkRE8VEOg==,type:str]
    VALKEY_PASSWORD: ENC[AES256_GCM,data:SOf59y6t8iKv874Z21VaCMc2laDtNwclnDQASd63HltWGnulnzRrnKcAgg==,iv:3mKtZYvI1nYK2aINgtdZIufaRg3DI0KdqRl77EkGlEY=,tag:N5Hrm66/MOPm1dRZslFzIg==,type:str]
    KIALI_SIGNING_KEY: ENC[AES256_GCM,data:g358q/wYhj8ABLAy5pxFpmCDFbGqMu1J67K8TbQbHstxFETFaqZnl5Z11w==,iv:EhWLsk99a48COa6mFDkyP/+dzdfnSxHKmd6T0oDoIOs=,tag:xEWSskUSySdga1SctD+ySg==,type:str]
    #ENC[AES256_GCM,data:okPi9JK8pyl8YQ==,iv:cLizPgys5wy+x1y7AnH09nC5fxvoRo9v03mdJpYfzxI=,tag:Q90C4EKjmmAEVYXX1tnE6Q==,type:comment]
    DATABASE_USERNAME: ENC[AES256_GCM,data:FDmQahRNIow=,iv:q7214Ndo9fnoqfEQrDU5rzJ1j3MD75kCaeGSbdh3/8w=,tag:CIJuVek6XR1caNFlpb3djA==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:x+yoe92n4xyIiJNRt+PJUOMwoiA86r7ibYh+zh3kfm4lWRt9RdUkVQSMMg==,iv:pnwaLhkP9zzF1VIOJR6fhuD3qP7rIt+lZB6ZoB9K5WI=,tag:fpiWJVR/gIEffmUpW7J85w==,type:str]
    #ENC[AES256_GCM,data:ZqTWulsO9B3pA9IQW3s4ca6J,iv:M/Lx41JvAltJHWQ27qNwfkXucUBRJS2J93Ujm0SiKek=,tag:xEXrU0/+fq3E4u5nGT7IxQ==,type:comment]
    CNPG_ACCESS_KEY_ID: ENC[AES256_GCM,data:ACOTyIaUxySQoFRlyQUvkKorYGQ=,iv:QJHzGpNY+td+i3HaZOj+IiZYSM8/ZHRYhajNmzbZ97Q=,tag:d3ngy7Usw9s61FtH/z/iXQ==,type:str]
    CNPG_ACCESS_SECRET_KEY: ENC[AES256_GCM,data:DHJxf1+CHl/us4FFMZW+3IXiEhNRHW/uuWEYGp8sPnNmGhuebiBRmg==,iv:OHXwVfesjIsc9IKiW6mPlTzfWdDSoOxMeGEXETvyGlw=,tag:dV0yZfcKzC2uPJX74KLTqQ==,type:str]
    #ENC[AES256_GCM,data:Z6nH0gYlaD+1sPPY,iv:gh/9K+n5MfN/Tm4n0ojIr7IMjxwo+LFhRV48Ml4SiQ8=,tag:KrmKXa/BmqRDzljSeZoBWA==,type:comment]
    LOKI_ACCESS_KEY_ID: ENC[AES256_GCM,data:X5BuOIZBHORnt+Fd3QT+boOrI6Y=,iv:AHNHnwCw0v3yvwBJVVpWzWCBhXocmbWtb04ILInUKO4=,tag:xTLCpZOCU8mnbke/VMVitQ==,type:str]
    LOKI_ACCESS_SECRET_KEY: ENC[AES256_GCM,data:4smhLLggFEEcL5hna4M0509Hb7CYHzHV1z5Vcci8ntILdjY9b2xr9g==,iv:WWmtk6zlW0DoAW7fZX6d9y3I18dsAmXKHd4HV+rKfe8=,tag:xMe9Ea9Bfs3SCptzKcVclg==,type:str]
    #ENC[AES256_GCM,data:lKI5GnTpfHsPtu6pdw==,iv:des1zjTvB6mip7HNP51JKHHv3xuLfy8NUM7tHwHWwX8=,tag:y4EXDm7Te1IJwo9VMzzYoA==,type:comment]
    TEMPO_S3_ACCESS_KEY: ENC[AES256_GCM,data:8NCBIOBHMb88xrqbPI3Ry6FBkLM=,iv:1wWBi9FTdkGr31/rrpCnzqAWRwhj/TLjElJ2OGSI7T8=,tag:ectLB6H2F0YqjwvGfUmQ+g==,type:str]
    TEMPO_S3_SECRET_KEY: ENC[AES256_GCM,data:dfwhLkakBq3qH3LjHUyaxIH3nXczOQNPq4p9D/yRNk+muIjBGsaokQ==,iv:lLPZD+o+NxMg1v0iEjddt0FmZuusUjC2otbnvarYqk8=,tag:9DtQ9OpLhPR+DPCjER06aA==,type:str]
    #ENC[AES256_GCM,data:+i0MW1KlomZa2ZfEcjM=,iv:iSZbSVn921CVvIEHIOopas8y3g1ibjfUahvM+PKJ6Ns=,tag:4toHh6KOWUrfU1yMMiQXbg==,type:comment]
    THANOS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Np1rYEbeg73+pYUQFvFvn35prgQ=,iv:zszWBVrLluRdzmJxScJs3AjCoTsJ6KgeRt9ikUzDKkQ=,tag:l0JU7WlnQ0yy3HwYkzJDTQ==,type:str]
    THANOS_ACCESS_SECRET_KEY: ENC[AES256_GCM,data:mkkfFQP8+IGnIlN7Z7ASb7DmxhhrV0Gq601znTh9U8BEZ6pReavS6g==,iv:1oYh0pZ514K3t6VStRg3EcY8rNbnhE4ZAE/HseGtxw0=,tag:MNlCwlwQeWnmKSmgyuh29A==,type:str]
    #ENC[AES256_GCM,data:gDd9pCY8hNNJ9yrE0c3A,iv:BILOr9AAIvr/SGwRqkYVylKki2+Uo7kAuk+jcdRPfTk=,tag:c2972xzxbV525DTIuX1hUg==,type:comment]
    GRAFANA_ADMIN_USER: ENC[AES256_GCM,data:4/XFu6M=,iv:9Oe66p7OOgM5Fe+KG9yQnbEZ5rkuCsXCExw4pWPZtWQ=,tag:uimbAQuJSSrJerKhE0Wolg==,type:str]
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:xLNAeGUvbMB/E3C8Cz3W0l0Xo1ttQ02MFkHX8Oe6kNbLlacpJwF9FI3fXA==,iv:WGVPp+jOlyHgmMtqkX/aPd7tWDDsqo5yRNFNHQBTleg=,tag:f70K8ilGP2fqaBhUT5F6kg==,type:str]
    GRAFANA_AUTH_CLIENT_ID: null
    GRAFANA_AUTH_CLIENT_SECRET: null
    #ENC[AES256_GCM,data:ClBteAkhnf4fj5oS3jQlRga5Kt3Rv0M=,iv:XIPb8EF1fOpLCxib65kC51zDaVw4aiyoPHfUcpwX7mg=,tag:6ZwxJmqZpS5aH20a4WB6Vg==,type:comment]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:tf7R2jvI4YBnQ+rFuvQXOslP6Dhl2KcsJBTcvlMh+CuWMxb1eC1ksSH/RZfHtg==,iv:wZEOgpALi/7oAn7vpZOo/VtsRa1kCkpc4WyLX32Qf18=,tag:9RQ+m3uhxDIuwQstOiW7SQ==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:DHoAYJU0PVKk5yA=,iv:u5LYKxPN2FjVcG4jyiULqpdwX9Fjv5HiWZxkV0wbEu0=,tag:khkNF3q4oik+3jAUDqiCug==,type:str]
sops:
    lastmodified: "2026-03-04T13:20:10Z"
    mac: ENC[AES256_GCM,data:dN9FDcXOVLHvLhUmVpGa6suHAPm3fzCQ8eX5ebNbuwKeaVJnTAzgSzBkhrTiaMt4u1eGGdzVg9RMWASgAFM8JFAVEjdXK0Jx0joO1aTRlAGQ6uvBWp9nSZjXH4ittBfSZQbiSUKGT7vXKsm69p5i2evgMjrjPFxM5zFNvrKSupw=,iv:B3u1LDK0Ht3oeHX3RyoKoWd0UCzE04fRMWZiH3aE66I=,tag:zG0XDKTpdoLfTelS3WpWxw==,type:str]
    pgp:
        - created_at: "2026-03-04T13:20:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQILA3McSkAh3rFhAQ/1GR/c4V5S8m7OvBCjMNoM1p3c1VkH+18BJvKM4BSqIxqv
            ll4KQhXDEJrv6TKSgH5oCQ8zB6yOpS1w6tiKutb8YFzozODpymslNC1qEfm+Cb+d
            DpqbmWB/7WCgbkl5qwJ3ZTtOD9PsqXGmm6XwuzLYR21RbIqlso57C+dmoqWiLTO3
            zNG2MfaTlEY1iBYk94CGQs0k1bR3w/GIjZGqXhtx2S+nneyxq8pUpeYGgr/ssEUv
            AxcEqHZKlkjJwkLiF8vqPATrMB90RgONvu1PBAMoekCOFG6uhau+SiCXH3BBH2s0
            b23TDa4gKxmqkIFPMvKSjKiKXl/d1dsJreX/fJZh9DA9aq5IvWapJuZVthmFxSVS
            evDPrPwkpQWMa2Rz9ocNhOu3Y5zEm3t5C3DC6JOdirL9UHBK/b7DGLnt5whIjXV4
            l4H6+JblnLbigCIJpwWgL5B0wH843aqjklXAB9/Dcb9lDyoRXW9hWdXd0CLRbXLK
            k1NmV++8e0PyCuEX+DFS9GvugDuDVd51sI+Ta0nrMaaW2puUcbczw0M5/FGtQLch
            V3lyrXT4dMmlpN3Lj5AQ6IN+9jHBrDMx24TTUPa4hAYyxqVNjFKfq9Rk5DaH6YvZ
            Gzho9aTlNdPwVQXQgxIjZZy3wTVSfzG6S7Mv9GZwE9WsTZ57wKs8kORTpwSbP9Ro
            AQkCECfH/3699C8uOjEoJCH2ZaKCivlbK5/reu0dCyxWw4KgaPJoQunJI61c9nZI
            kAIar7W9iVS6+dbPAdOK+4QH3F95THTGGNnL6Rpds5SXSsUThjWHNFWl3Jjpmycn
            BzEB+kZGHGc=
            =mFmA
            -----END PGP MESSAGE-----
          fp: EF552EBA773641B396D26658E1F56350C447581E
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
