apiVersion: v1
kind: ConfigMap
metadata:
    name: environment-secrets
    namespace: flux-system
    annotations:
        kustomize.toolkit.fluxcd.io/ssa: merge
data:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:JeXz2Y9T2hoCe3gPPmORCqM3a7cUYOp86okDsO2IO/aoBdg9j2N2Tw==,iv:Mi30YiF1ZmLj/ICT9bq7alYX7r5QaGOY9cwVZO3TG6Q=,tag:LINoELUBi6r02qM+SETD7A==,type:str]
    VALKEY_PASSWORD: ENC[AES256_GCM,data:VMRGX0TEpbotUlZ33Jp3vvVoat2LAhjojIjyjCd21QDk8jZL7G5/ozVIxw==,iv:lI+5tv852QDtKz8myb2p331IIxWC/CKzmwzhJWtJbBU=,tag:I0OnNeiIH1VZyjZARoH2rQ==,type:str]
    KIALI_SIGNING_KEY: ENC[AES256_GCM,data:M0g/sHv8JuJKQaIf8RiLG/aE3/h29LzB4jL9y1MBpKgu3E/XfD7CYP8Zpw==,iv:QSxFIs2QdXKdwGM5JUvoQWWaxLNYQs3YGMGDe0PWMe8=,tag:Vq69GfY47lJ49XOIiOojAQ==,type:str]
    #ENC[AES256_GCM,data:A81zgfal8dL86g==,iv:WstJ2ROEkKbEqQpASHWCPGQAH3eACFRtIiWoQnf/xo0=,tag:uk59tzRrk1FJHN6VE1p1mQ==,type:comment]
    DATABASE_USERNAME: ENC[AES256_GCM,data:YcMgeGKLwh0=,iv:EDSnjSbVY/AAlAv13GOeXxbFtAB/yFE0YkOfCUSa6fU=,tag:eN8rsHN6Ume7Aq4J1YLbHg==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:cVf7eLypKG98epguaNoyoq/hvkGLCmccfAm0aPpRm4MGYGlIZfxXQs6O+A==,iv:qNtQkNrgEqNwRmWG0VxHWKxzZ9bioRN+CCU9l0LOJuk=,tag:Vwfv5a8xdpeb3UdUbvb82A==,type:str]
    #ENC[AES256_GCM,data:cwWEhqQzLai016enip/qAdSs,iv:4h/yW7+li4jQ6pFwjcjE8+BF/Pkoq1PU64Dmn6jiWoY=,tag:5DySAyMo0jkhyyJeaZ0HLQ==,type:comment]
    CNPG_ACCESS_KEY_ID: ENC[AES256_GCM,data:RnmqSHq1h1FMwlKR1YFfUY58//8=,iv:oZDpujgT2COukg5PNfhQT9bZ48Ynu/7pBJs7MfmwMYE=,tag:prm8QYNCR5xg+XVgy3FHMw==,type:str]
    CNPG_ACCESS_SECRET_KEY: ENC[AES256_GCM,data:AH0lFu78SFgq5c8WjiaW3iahjfrkSKtx8OWdOzeg18bLKhBV8C4exA==,iv:1eDNBIlNps3uc3EPeUEazhW3ewas+PYifWyR0zqon1k=,tag:K95LV7w1VHeID7/v4pv5Zg==,type:str]
    #ENC[AES256_GCM,data:FAh1VAxzTq0eUelq,iv:oE92lSn+c1r89yRVUrjd05HbujUohYc5Hc3nhSZBVVI=,tag:Awm2tFJEAk15Tu2+Ysqvfw==,type:comment]
    LOKI_ACCESS_KEY_ID: ENC[AES256_GCM,data:bvtBLbYkRJiw3zfz/3q1ud0eTSo=,iv:nuH8ZJ/wlOgidILsqa3PA56fNctnhOT1/gLbqYsUEfI=,tag:gOfxgBGCooJ4HocaeMBT4A==,type:str]
    LOKI_ACCESS_SECRET_KEY: ENC[AES256_GCM,data:/K7hoegvwo5HrJvR8c5DShiji3AR9Trlb2UccGWvPtj9GiI0Ovpbhw==,iv:200yCjTVgrGzLJ+R+N/qqE2ToiwRCHchrFF32ngozSk=,tag:9udaL/1FJ08677sdiWnkhg==,type:str]
    #ENC[AES256_GCM,data:GzxgdAuz+vOas9p0+g==,iv:Av1eO8V3IKzwlYJO4hfQK5pONmlcSc3NfuHXQ6Z7Bn4=,tag:4UFPeJuqtNU5je7keCVxGQ==,type:comment]
    TEMPO_S3_ACCESS_KEY: ENC[AES256_GCM,data:JfyP2qjGXwuptfi5RJF1LXzuF5A=,iv:XXNJtit2CnHVU4nFqFladgIPUX6iMwYe6BMmwj9nI1E=,tag:OwP5MHJh2rxSE5LyQ19kAA==,type:str]
    TEMPO_S3_SECRET_KEY: ENC[AES256_GCM,data:D0Fyd3azMUbWA9liig3mE+40VGDcp3mtJAEeNyClnR+vVCZNQKo25w==,iv:931AkbGCh9DMKa8SrB6S5yfNDwIEJX21wmBMPQnNUWE=,tag:k1NNDo/ORgz5uk8SryS+fQ==,type:str]
    #ENC[AES256_GCM,data:w7jpVE4OGrqLK01rBRU=,iv:Nx40QD6YZNWVeC2BG3VSAhyKYxJWh5G0Js5zWd7S3HE=,tag:RI5v8VaLkRrvBdlUvbHl5Q==,type:comment]
    THANOS_ACCESS_KEY_ID: ENC[AES256_GCM,data:pRXH7W/yuv+dGLF8tJh2FW5wnRY=,iv:P3ydncVBW+gIstysOhQXy7CUpvDTNM4RIvM6jqTNjgE=,tag:8QD1J0JYScsuSJbiDUBleQ==,type:str]
    THANOS_ACCESS_SECRET_KEY: ENC[AES256_GCM,data:8G1e8tHhabI2Sqfn0odEUjZ6po4z8rBzHnhc7JOglNUqKVAq5rAtsA==,iv:dt5sopTtXlZxRDs3wd0q1288BiQ6bUY6qDABFfTh2sQ=,tag:b6D4g6TbdQmqBS39Lw0REQ==,type:str]
    #ENC[AES256_GCM,data:4uPSPWLUgrCHOpmOB1oa,iv:GKAnp8GQlIK6A3/KNQjLeoyRSkylA0XVevEvw2aiFz4=,tag:jzuuCRR9RH4yokbvYakj6A==,type:comment]
    GRAFANA_ADMIN_USER: ENC[AES256_GCM,data:I+rV//I=,iv:0iTRNBnnbh0WdodUXKKvU6UFImQcHzk3svF5DQcfVXs=,tag:lPVVXMPdwx8n+7K6ZptoCg==,type:str]
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:8QB3q4wmCxtfer1bGM1Znoasl42jbtJVBHLDX9sH28XTmIlspen1Cl9b6Q==,iv:4lDowg+C0dS6/GfqlDif9J1qnl32Itr22M8q2QVHLMQ=,tag:FKRJAEXqdMlIZl771Nm6/g==,type:str]
    GRAFANA_AUTH_CLIENT_ID: null
    GRAFANA_AUTH_CLIENT_SECRET: null
    #ENC[AES256_GCM,data:UFCeQX2HN0+0vlPedn6XpUDOXluTYiU=,iv:FfXi9LuXEGra+hfwwSES+SEbyxgzG7JKBRfaVCJ+f18=,tag:7oywStzKI+DkWi2k9Yb+cw==,type:comment]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:MkhsjzfP3YDZaU57RXu3HZ/NBOm+jb8QBcier30rugjdf//ojNkrxe72rX8m0Q==,iv:om49ToCvWfAeZCX6UNfc89/flCas1Zf1qOOIzJmPHi0=,tag:Wlv7YWfOqA/DbtokZmmlZA==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:QwO0s2waRFJK5W0=,iv:GrdV0sKXyyAsJ1340NoboewPMA0qVrdztad9P/crOJA=,tag:UmpbIfxmC7wKOKleHBx1rg==,type:str]
sops:
    lastmodified: "2026-03-04T13:16:29Z"
    mac: ENC[AES256_GCM,data:NIBqaKbFbnVHWU7EpJoYNLdLMVBOB8A+un+lmnpJoekXNLi1CiQFXlhEJwGdPnCHIzshp6Q/QtaEnWQlzivgxZ0Qf4THSlXTfY1jZqEeH3ycRzODPY2YpNFeDNC7VWWuDPihulVosrum2g19HL47ih3vir0iD7Yk9l/XSnuQ/Zw=,iv:cibRG7MgiWmj89PcF7ySAUhg0lQ24alRn4c+aLJTLaY=,tag:7cSDZn/OKzY44QpfyNoGHg==,type:str]
    pgp:
        - created_at: "2026-03-04T13:16:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3McSkAh3rFhARAAn02hQSVCo6Jrp7I23bMsdniaEwY4/xgOnFsryRELaMkf
            BW6A0PlirNfnSAsNldbfR/7neQt/dubIhNipEHjMbxUS1cMpo+8rZQ/Fm47omEqN
            5k+iFYmCJKsMnZnOJ4rervGVhlmpw8LEzoeOjFxBtHMDWcD8qrR/1jVCDm9q2gLQ
            WiL/++N0v3NrEW1BLxQOBRTqCEk+tw+DtOIwvmETOVag3Ri/mxwcSfFeifGMuO0K
            YgT8/QN1PFVoZl7kNxFhoMllSjJlbiX5np0uOoDuuPEeHopD858bWOaUdw8lnFxX
            3qUn8HOdLRq+W+tx8fNJ2kbbt5OYvTNJM6uOQRsRhsoT/wNOtdtw3CXcAURNY1mK
            2kiF2/p526aLbflPhINVvf0Fhr5W3V034ZsG1q0zkCtBJOt8KSQTnKvYwJ15ffeZ
            VdTAhmo8w+hA3WBF/fXnVU5Gvayt4UGH9nVr1v1rgQa5AZJgazkiBCHypr0tnNj7
            +z/Cxf+fylKP9DT1FlEF+1mv3bNC8lbk7MY1WTaHJPymUSm/H6lY1qbkOWzQgygq
            KCEnL9d7KZf00ju3Bl+cwXwqbSOK62dA6MfVVo8UitOqxUSsnwEwI23TLzhAhycs
            urx30+9eRsVPBt9UOD9D9TdEUBsfPwQ8w+NnDaJCD5WMpetIXfO6dsd565ItKyPU
            aAEJAhBobMQYGv3RqL426H+56m4mhU0ZFDy2M8dkoNI4ZJR1ne0NNoHbCf6K5wnq
            D8h2kKKWZWgJ7Hg189uIM4BT8uEe2AWUEy3W9qWifOxRjRxKgdnwzqSHuTwu+0V0
            6fo3vHTrk5i2
            =lFS7
            -----END PGP MESSAGE-----
          fp: EF552EBA773641B396D26658E1F56350C447581E
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
