apiVersion: v1
kind: ConfigMap
metadata:
    name: environment-secrets
    namespace: flux-system
    annotations:
        kustomize.toolkit.fluxcd.io/ssa: merge
data:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:2iYpB2fYYYxE0pX9pjDSRo30qD2r97iTouGc0oJNqqoaE18LUNie8g==,iv:KTE9XpdpbvQQB9Z6oFB559/RrS9ah2mPjzR15IRKIE0=,tag:YgEB09lauv1YehzjJ+3Ieg==,type:str]
    VALKEY_PASSWORD: ENC[AES256_GCM,data:sTLZ5rABPDtTy+TCLsTfRFtSz7UxMeITo0saxz8i7VwZdsFjYJluILQ2wQ==,iv:X6wU9DXIaDnpCjS9UUUI613tQEghSEDzSHS7orEk1xY=,tag:LqPy97c9JsTErU4xsT+mlg==,type:str]
    KIALI_SIGNING_KEY: ENC[AES256_GCM,data:kOWhfxF9A5pP1Bax2hyUl9/62rrtsrFb4mL6pl3a7IRptjM9D6b4/igm9A==,iv:+VBqAyZwFaRGTBYqliPudb9N9YZ8jJEGdx2PlqXmYBg=,tag:3f1/VeTinq6Lp3A0wlODTA==,type:str]
    #ENC[AES256_GCM,data:zo9Cch7ANuOvPQ==,iv:imR3Ihk6cDXGw764f/NLw16/iMhl1zX5Wl4d9W/P534=,tag:0ZCioVwqcYc64tvB2UMQ6Q==,type:comment]
    DATABASE_USERNAME: ENC[AES256_GCM,data:Mc4fIz683Q8=,iv:jbnrdNOxhWW3BfkP9fI/KqltDqBfqXhY2B1PlTQ3twE=,tag:5d8YzOJ1C0X70VkBsv8UoQ==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:W9QpGZN2lBerXGRRK3RO69WBSQp8n2DaECVqH+PxtMZH3rsAPVHLFWmysQ==,iv:Y4zOod2bPkBOqhsikaTPFS/TuWxye+8fGnq/rep0BqM=,tag:MZTPlfFlpdQBJvrE/Zd0hA==,type:str]
    #ENC[AES256_GCM,data:vqhcgsASVTqfi9txVRoWL5am,iv:gFFmqGS+riOXdGRdD7/JK/XnXoSfNkie4RgtwVQV994=,tag:g3qPKityBFM2ZHijXHfMBQ==,type:comment]
    CNPG_ACCESS_KEY_ID: ENC[AES256_GCM,data:lSAJimKA4SBCe8AiGEhdr2hpq5U=,iv:E1s+jOTDIsj0zOYyr/zRKYOE/G9T2l2XEHB5AFTHzXo=,tag:oX5otUUGIS1jxU5p248Rsw==,type:str]
    CNPG_ACCESS_SECRET_KEY: ENC[AES256_GCM,data:S3jOy/cIiyHJYoM1lo/5TCtRBPSyfOooVTY5hr9IHGzcaBsHjsiclg==,iv:quubC0G4oc7UnOFQsQ8adUOl44dg0Wr+unHHNpQNjiI=,tag:U5+6pbGDspOLuWaakLmOhA==,type:str]
    #ENC[AES256_GCM,data:EdQM6AwNkVdNjQBX,iv:AMuTXubzNbQNA31GU94vQqwLoYvp4l2T/G9ygo7aImM=,tag:CP6YuQcC5IFt8W7dNVxwug==,type:comment]
    LOKI_ACCESS_KEY_ID: ENC[AES256_GCM,data:8M9Th4eoikxCI308aSzdCLt7PVE=,iv:xNZf8g1eH8JwNR33lMhOUaUpOU+gT53V7G3pQCB7YZk=,tag:v5MBD0aeP6CtJpM1c3Og/w==,type:str]
    LOKI_ACCESS_SECRET_KEY: ENC[AES256_GCM,data:0yLDbRWDJghv42jtznmuX09ouHlNi4Ya5lvAGKiBaX9FxZO3RcGdrg==,iv:t4k5kcSI0IgLsbTV+vdbcXlNnTDEgKf3MMXHrmHzlcA=,tag:NtUAG1GjTtIoYGPWVjhNCw==,type:str]
    #ENC[AES256_GCM,data:JJjdfmFtYDt+wBk68w==,iv:hXlqsxVSfIefBWaWGTfUNq41Qt6xSknIi+g8l2N1Ikk=,tag:pRY4bapxcjql0uSB80lmVQ==,type:comment]
    TEMPO_S3_ACCESS_KEY: ENC[AES256_GCM,data:jwqeZKDl9SJFNynozkx4g2opHbE=,iv:CCJPqU/GkK/ikAi4LsWTzfD5x+gsgfF0PKuTUcRqiYc=,tag:k96S8MBYANbRmcFCcZC3Lg==,type:str]
    TEMPO_S3_SECRET_KEY: ENC[AES256_GCM,data:1FNFxCEnSSSAvl904JyQkKW4mYr5NCA5qccyOVGw4YLhmdqYHakLRg==,iv:OJtWiTcqqlBK3qRJXiHz1zerqVoi66hVDmSsml+TC/0=,tag:doOe0IcFXVpQuBR8Xzvanw==,type:str]
    #ENC[AES256_GCM,data:ljDErbHEdtIBlAeFVEk=,iv:HTbAC8a06f6yOYKYjLpPuQCnA9S6q6eXAxiTaD19lo4=,tag:xFGs6FWs204gLdTZsOyUpQ==,type:comment]
    THANOS_ACCESS_KEY_ID: ENC[AES256_GCM,data:JoYbwDiKx9GmhFHqVjEUISuw8rQ=,iv:6dFdp19+KecXkeW8dZ5YAARIUz1yBcvRQdn8C+1xQus=,tag:kJmlcSyjIknMXx93dtAmUw==,type:str]
    THANOS_ACCESS_SECRET_KEY: ENC[AES256_GCM,data:966Rgy+DuM5jZVlhJcJGE7RVBsQik1ZwxK0Dse+IUBx/zpY4d1Hxcw==,iv:J/ipaOW0lgRx1dfOGfui7YKrtesyHLMxDd9NR9zE3iE=,tag:CevzWYFgQw++5BYxMFx2Cg==,type:str]
    #ENC[AES256_GCM,data:d74gMwKi03dXJIxGUjUr,iv:yaDsgQZxP5Z2aZLt9TmzwgxWFQcY3vXbWAXJJDaQj0A=,tag:tiiqM0pLJYUdQnViKnRHUg==,type:comment]
    GRAFANA_ADMIN_USER: ENC[AES256_GCM,data:p4vYYT8=,iv:ocFt2UQjHRclsRRZS1bvCcKThAbCIoevQvgC5KPZEMY=,tag:dgGgdYJugMMWuHT3/xKFBA==,type:str]
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:wnpyVuGKtRrCg+LPlSSL/59wdxqah7kaq5VCl8c3YDehbtWi8HiVO9+i+Q==,iv:UNyn2NDMLzVbRxF9iNzOd6hQyDfas/VqWSgPUMG/7vQ=,tag:PcPWLSrzyIoHrZgs6L9VGw==,type:str]
    GRAFANA_AUTH_CLIENT_ID: null
    GRAFANA_AUTH_CLIENT_SECRET: null
    #ENC[AES256_GCM,data:7hQI/VCLV8TET7+wBRJbNEvpBECyfJU=,iv:mjq5yicWWzRNFXdR+9mBZkIm2g2k0r06+JGi9WWJJ9g=,tag:RGLyuS4UJhSTn5KF7NpFDA==,type:comment]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:pZFgnIwMkqd7QVP6IHcVvE3C0tmAQ/zFrWimnrGNMsLvTW89Jn/fzLGnQfNZIg==,iv:pZykid2GQms6LGubhchqE4BuwY14lwWSTUl/XCC29J8=,tag:iUiqx9wHgsHM1jvReWg7mQ==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:bKV7GCH6dpoValk=,iv:lXpOVOqlQpaeIHR8PiGok++vq1kAMHkCBiX/EoSFbQY=,tag:8uhMVU+0GTyLU+JTWdPlMg==,type:str]
sops:
    lastmodified: "2026-03-04T12:03:45Z"
    mac: ENC[AES256_GCM,data:NWpjV7YisxugL/ZlgJfshgUPkKytY+DqeHz7FLV4w5ci9FnZ/U7W9w4ec5uwMqCwZuquD8jQvWNqDZ82mdWVrwu+7ZK2XVyhbiW2gVIlhoqWMfw6ZJSbni05zKqF+6ZIg+mlMFpKx9qsHfVAC2qHn9dGs9XnVVRjGCgh2RxapxA=,iv:AaTDAo7dQ15rPEaGQdr6I4LCWTEtss5JnRc+afvh+KI=,tag:NfxmqLppWtdgPqAzy3rvVA==,type:str]
    pgp:
        - created_at: "2026-03-04T12:03:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3McSkAh3rFhAQ//XsGiEN9NZukzwwxd5nmsSUv3HJkzNd724qGtr+AqLnjJ
            WNgrArATZrHzWBA9a1cA1T6u0jAQb6o05gKS+XFNgnVQljtpXyRbgpo2qXioK2VO
            lw4tpzXxRXO7sCEXgGgses1zaeCwbiTmGUzEvIADmhzCRychBA9oN4vpiHhqcDH8
            Z8iCVGZjDshZGppSd0KTel9qEpQd+x+NNQzKhiZNvJpzHFxXCVJKT/63h9EoDCGW
            KQxIY/wNONa2hD86y7pkn2tEPEmx85p3iMC/o3j91zQrKWgSH0s79rPVh/kAaPc0
            gBTuAE5v/U78/3HdULYxBlWPhSS0wssSNXvFli8CaByPoAYa6NStjkwoBkNjScVN
            iA7cSPRYxBxyurBk32xdFw/kN8KEFdYofrgwG2tybbTRrylfuEQWTr5mTyIpfTmr
            LR2doQlAAf/08H4UQrMj7HpqoxzXjLRyts/PE5OuBgW+z1vHvx7FvLnf/8Rog+dE
            AYcBn5TlFBZY4BoRAZtZunvGdqCb9kuZ7fShOswQUH3M16VLWqT1mFw6JhaJGqs+
            z9QvLlVCPxMMFly6b+A6+0bd6WbVBD15qaFL5EUfavm9lDylKyCROuz75/s3RBgZ
            75h7X2W3FSlFDTzzt+eeHFfEtuTWP41GzkuA5OG9ThO2lw3+5PeigoVJBimZUBrU
            aAEJAhAc0/QTEyECJmTNr+6lTxDJBfax0sKoVWk6m1TICqlkk15QGrtxAYuq0nQd
            LuErgLqehm7FDgNB22GaGS2sB0chqKd9kOOAQEPANwnl0jPK6Z2+bUfKuzTDLTQv
            HfGaEB5uTyQ3
            =11O3
            -----END PGP MESSAGE-----
          fp: EF552EBA773641B396D26658E1F56350C447581E
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
