apiVersion: v1
kind: ConfigMap
metadata:
    name: environment-secrets
    namespace: flux-system
    annotations:
        kustomize.toolkit.fluxcd.io/ssa: merge
data:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:54kg4jMjFnBV3WkA+6s7FY3z5tnLJ3YBZl5eyaNRG4HFrFBCmqlFkQ==,iv:rMppl4fF5DSikVmzj+GAcIN4BKjQsNy5g6CoJZn0nlA=,tag:QibtaptM5Aitg3ngJpoJ6w==,type:str]
    VALKEY_PASSWORD: ENC[AES256_GCM,data:e0DdA2X1w1ohxINgixNPRTavisYb8wITJKYKp5EtB6eVWA11Xt9CMWZ8rg==,iv:WhzzTlR412RpI97RnkA9ylossEUS5Xaaomgow4HVCnk=,tag:xpqEv/IYzum4tV7UZXWn7Q==,type:str]
    KIALI_SIGNING_KEY: ENC[AES256_GCM,data:WidIItAwBoyqRpelqRaXupBp0yzqos4ytKhW1yO3D1RiZQMhlSWf9+5pXA==,iv:J/SpaH9BDYRKvM4nhgwmn/KlpV16QYXw+ziT/Jiw+UY=,tag:7Orvoq9oRVO+LLS0omGkJw==,type:str]
    #ENC[AES256_GCM,data:59Jy5nAJne5iWA==,iv:LAUT94yy45lJS4sNYoifcMfK28pomrvN4xSRFnuYJoA=,tag:RJaHmCIG2jPV9yDfW7f7Ug==,type:comment]
    DATABASE_USERNAME: ENC[AES256_GCM,data:PgnETI5NS9w=,iv:oiGiwATwiH5T4wOKYF+uF6/muVjMLJiL5hGDMt+I4qI=,tag:gfrzHe5NRI+Vtz/vI5sK0g==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:W+rFiAjzO+SOUa2iI2S0FxJNsF/vZGI6x0kobc/7zzCAvfec/V/W8zoaPA==,iv:49INFPhaFwUI+ixv6PJNwdHyhd+DQjVCbZACEyyo2sI=,tag:FRlkVfZCWFvLO00Rhbbn7A==,type:str]
    #ENC[AES256_GCM,data:C984rilDqnGBjywmLHWqNW4l,iv:Pp31Ym3+6e4w2agIQYjRxU+UHyXzrC9R4SjQqtVo0UA=,tag:bOQ7ruJ9WLQ+82yCr1LMCA==,type:comment]
    CNPG_ACCESS_KEY_ID: ENC[AES256_GCM,data:LhMzVfyJF1YmvkCVNKxtrG/DHLY=,iv:70+JuYYkAuqBMw05kueID7cj2zMwno737x9XlmVATTQ=,tag:jGlL3HcGK/qgmW0W3tyUEw==,type:str]
    CNPG_ACCESS_SECRET_KEY: ENC[AES256_GCM,data:DhzEgr2PowpYjPfNu+qHCdbUoifOK44V/OH4spb0R6Xymm6bm5Tqww==,iv:m22BLlcm5kCGhbTgVOqY/Jj7SXul5VLI3WPpObrzTwE=,tag:o7rgBDO7MvwQeFpjy52OVw==,type:str]
    #ENC[AES256_GCM,data:qR4aMIjMtvSzkf/E,iv:DWmR8XFtAyUvA6cAO8RAtm5MYVbSVQfhtmcVlSxsPdE=,tag:GnIkYJ3Tg/P5yx6LUwhGYA==,type:comment]
    LOKI_ACCESS_KEY_ID: ENC[AES256_GCM,data:PovZM1vVLUbZMbbD3Fd2vqwu68Y=,iv:iCsQXyjPzJoXzt/W4UlcqrYte77UhlCZssNO+tltLyM=,tag:s9Ti2UDCo/6LccjWPIMExg==,type:str]
    LOKI_ACCESS_SECRET_KEY: ENC[AES256_GCM,data:fMVjcglP2HxT6FzBAch+/NrfrMqekRO3V7DnpuYpYDMc0XQBjDMsUQ==,iv:pap0uHnYJZ27mPIXXsRnT4s3yFpk5ICM+6XNqna8qeQ=,tag:vvUFXPodCkWBJ2pdV/psUw==,type:str]
    #ENC[AES256_GCM,data:0M6y0BIN8xj9g9Aonw==,iv:vrhdffMf+K7KmYdeYJx4cWBQM2oYYWO+DKRLsH7pZTU=,tag:Fh18ySCEug21O7GsbmY4Tg==,type:comment]
    TEMPO_S3_ACCESS_KEY: ENC[AES256_GCM,data:km+7DSqDQNKrYUeEkv8z/LNlPww=,iv:9hzjYqyvhhhi82ny+9dUZfhXfTLXpRHez+8dLmuh7Fs=,tag:va8Fx7W/OpMJTrP1azXMLQ==,type:str]
    TEMPO_S3_SECRET_KEY: ENC[AES256_GCM,data:mVJogiuIiFhSnGVxXPhkzhFDDEbDeDzcgYEGyGVcES5iMhy2Y/2A9w==,iv:08xcxa9+JvgFHsOcvPg9P/GYxJp5Lv3+tOOLdUPirr0=,tag:aDaKqxSe+JNv7Oj+OEkR7A==,type:str]
    #ENC[AES256_GCM,data:tYElRgSNHz/vwn4yEus=,iv:j2wSPl0rF69USPkBL/Oq4aA3XBiaMWuNfgkdhLZiHCU=,tag:+pXbjIOkdckn8XO8ginRZg==,type:comment]
    THANOS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Fr/Ra/GCXwok3xHTQ8EvdFzIrFs=,iv:lF8InV+AhdPlR9UFp1nwcmUF47RWodaN2zdeV1A3LOI=,tag:cXLd+opdg7Ou8MSz5TlZIg==,type:str]
    THANOS_ACCESS_SECRET_KEY: ENC[AES256_GCM,data:7/6FSoqVn1ui2j425cQmLBC35oPfuz04iaFNQFrJXiy4W9fr0Wwu2w==,iv:XjCskVVf0oz3CJbe1QVj2EAtzGB/PBNnTvNpX8Zqudc=,tag:f8ngIovFYzR9bFeD1BUNvw==,type:str]
    #ENC[AES256_GCM,data:57cyVFsZhGbJjpZW1sjp,iv:bKtlAZat6IvOV5I9ZelWJI9p/ZpwczDNRig/hwAC5Vw=,tag:RCqZtUkswCWwbFzZizKaqw==,type:comment]
    GRAFANA_ADMIN_USER: ENC[AES256_GCM,data:y29FjIc=,iv:R+1o6ozbVaImL6FUvr4qWWUVS57+/zvywiuBpcC9h9o=,tag:c/kQXsvvu0B2DVVpBwOiDQ==,type:str]
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:2O0ZzlyRZdOgK96y+08iayZ0+gJiwkULGJp+Hbef4lweepgDejq9x+JHDQ==,iv:Q5SqhyFEz19lRZkwG9U3R+QWPwFLMre+oq+h0q356Y0=,tag:LCxnNk50qZA8yNFFi5Sx1Q==,type:str]
    GRAFANA_AUTH_CLIENT_ID: null
    GRAFANA_AUTH_CLIENT_SECRET: null
    #ENC[AES256_GCM,data:0C/Q5ds2RgZ6N7w20S4ewZwX6bLpjWk=,iv:oer/ybTNyhw/SSQJk+vsi+bSb4CKuAWBz0yK1JQvlkw=,tag:i9W3mCQCqVS+u5AdCHleGQ==,type:comment]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:wAPMhf5I1yMDjb0t3JfEM2lEY4awhJmEXSyO/rBRJ2RSxr82P3YkjC3/SfT7GQ==,iv:zsrfwbtPAtrwYnAMytFGfibM+06zOWxiEhboG4OqMbw=,tag:kO26h0CWEEYE6i/FDG7/lA==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:RRwYCvJ7OSr1MtA=,iv:+zX8AtC9alyC2fv2S37mVIAolQ08Zpznrfn644d9eO4=,tag:q4bbsP4uQDLrCVCfKRDmbg==,type:str]
sops:
    lastmodified: "2026-03-04T13:17:40Z"
    mac: ENC[AES256_GCM,data:ps9q4c2potOG4J9hVlZBOMbklAga9B9qC/KDhjPNxXIol4yFKBX0TRmfNKWqoU1SribtspwS7GjMuqeIOGumaEf0+RX++YGtMFSycnNK1rUPJ5ruGQ1n8c1pTVTQ16QlpKmfyLJKK/8raf/mfWZa+jNBYTCQleW4q63FFZnj5no=,iv:vAyMyGwwdJofdpuP+4WwS/TLNkeFgX2cwZdZy3/cy5U=,tag:tpkIh0hoPWgyyEqHb1FedQ==,type:str]
    pgp:
        - created_at: "2026-03-04T13:17:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3McSkAh3rFhAQ//SNb4dlVPtbm2iolETsCtbEEXzbrS2uYMgn8YL5ls5LTR
            iXhkM2fQJdot0HTf+X86FtySS5i5ErT13ab+KKdDreuOUj2AzqYRl3AvI8HVeXt+
            RuGH3sYrjEKyKAKL3cuHjg72Ff/QqW2inzrUJipHdD3OWa1aDztlNJYxNErEnrtJ
            O3dWFnK0kUymDWKPr3508/gHE7N6qr5uEmCRpAznTeZp4zgMfZQxKTZiqLKCRpqG
            PE3CGDXPatLd5U/69gIRSQKD3MCQLC6CGzptllJYwPy6YxeCF/2SeljOMlrbZYnN
            dkFcoAgG07jGDczY22N21kKHbKVhDbxmkGu8JKp5OX0R6M+9R5j/9/4ifXJ1vu2A
            JVAR1H6YMjK3sqEu3YwAwO50CDcTKdQNggStlNfH2IhuhIktP2KADMOIUCjnsKSz
            naxUzipJe/YQsa8/ClZoOiQiOFJN48CWak55VM4D2gnDwsAwce9ioL87TQLcZckj
            uNBMr1xBRmQ62ZHl9i0yckz10jWS+rlCrpVggreOk4vtNi0d2iGvZPWP8bZHT2xj
            RKBvOQbCnkxTjLERSRiOLTUjXukb6JWPeLqMrRLlXs+QGgoVpKgqST+w9mv1OU+W
            enVaJ6Lg+9gqBheD2vuMfAFqieNG4u0SiKNy77UvPhZ8kQJ7CqVfEDGvPjQl+HnU
            aAEJAhAXbt+Tx4MVsZC7tnVp09UoB9wwBqMU68hQG6BCpdym11V4sNMk6UyD7gzk
            1zlcoKDFhpHAP3zU+gvuCn9RY6yePROeLKaNDCptaWzmCzO5/EXFXWoDefEGVKv3
            YueqATfMY+WZ
            =7Gj5
            -----END PGP MESSAGE-----
          fp: EF552EBA773641B396D26658E1F56350C447581E
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
