apiVersion: v1
kind: ConfigMap
metadata:
    name: environment-secrets
    namespace: flux-system
    annotations:
        kustomize.toolkit.fluxcd.io/ssa: merge
data:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:P9q+B1ZVTVt7mm263YlzpA9HF1rlLDMaJEDlxo0PIcSJLHfch2iEPA==,iv:gnd0YesWwHfVk4U25AGPAeLAex51wObFSi1MGz1RnSc=,tag:PL4RsMJfHuJmAQcHaL0l3A==,type:str]
    VALKEY_PASSWORD: ENC[AES256_GCM,data:TRZWQFCrejT/bdhYJwfV2dgt+c/4XZc0/bLpyyHNWpZIX2oX/qS+h5AJSQ==,iv:vUdKV5RGpuwoP14uEcnM/k/47k35g/R2nDMh9n6XK6c=,tag:UlpbyrkAwM4GQAjn0TR6pQ==,type:str]
    KIALI_SIGNING_KEY: ENC[AES256_GCM,data:NPXr4y3kwhCgP+TjJo63Zep+V/QuIYuAzDsied2puebP81fgth1jGfKR3Q==,iv:oi3lEx7+JvlZTM8943OTuJ138azYIYp1zkSS5NCKpdA=,tag:uwV/U6Sq6mviTsMD19zu4g==,type:str]
    #ENC[AES256_GCM,data:PL4jAYvZSi7HwA==,iv:/28mNFfgodeKajAbHoPbifNKR4fSq4AFZpfHgINfwqU=,tag:ujWrSZY3bIeryUr7eAvQlQ==,type:comment]
    DATABASE_USERNAME: ENC[AES256_GCM,data:5yNYIYzMJdU=,iv:qLROiFbqSy6wZKlTGrV6vgj/pZkaQFFKzxnqWBQcb5k=,tag:snJBe3TBLqR7PB0tyK4mJg==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:eef6I6VGwgErcsZl5z1DuC8wJEVdBpPwDjIOWzpmrQ7W73qEdl8aeaqwMA==,iv:BnAIViaPhDWrEnnLLoJx5cHPQErXiVyHt6Wh1sEqUqA=,tag:/AfLuAV1rpkwATvn5mar/w==,type:str]
    #ENC[AES256_GCM,data:jiiPjcpCN/w50FmLcqDj2AYH,iv:l0xMkIpaA93EMIXyvdD20zlE4VIrSlYU6S9ZNNs8qC0=,tag:csR/xU86y+6EjbGF4dPbbQ==,type:comment]
    CNPG_ACCESS_KEY_ID: ENC[AES256_GCM,data:q7JiP7vlurbVRBOZqGePwSJxxaw=,iv:6MR9ky5FKEahP9RGKiFZCQA/vi/EWEpKbIK3NN/YMdQ=,tag:981hKL9kgZdUvDeyMOExEg==,type:str]
    CNPG_ACCESS_SECRET_KEY: ENC[AES256_GCM,data:+8ntvO3mVdT891sT0+OTmy1lRPcEgcP39QuCv30urddDhh5h5CR0iw==,iv:e1MJRpssPWrjw9DG8QNKBJScmR05SIOSrvw79zz7ZQo=,tag:hZVAEcid2TD8NHzk/k/8vw==,type:str]
    #ENC[AES256_GCM,data:ANIoAQujfCBHILQt,iv:LXNOpdh80WDYWyyYRpssNMmHCYul88sd5sYHUzAB7NE=,tag:JyEwt54sfJxKqmzLeMmG3w==,type:comment]
    LOKI_ACCESS_KEY_ID: ENC[AES256_GCM,data:a/qop4TJkRIk7cIvwvnTglXamN4=,iv:KkXM8ZpZa+bVh/nEscWxT5tb6tqh8jBVjYCFjhyLnHU=,tag:exeFru2W7NvqmRPqUA3puw==,type:str]
    LOKI_ACCESS_SECRET_KEY: ENC[AES256_GCM,data:6jp6qGQhLQMXcDY2yY5Yu61WPvldcbnHZDD6m2irMvkmGXaanVqXAw==,iv:t4aqqrJsS/pSVYY3RetwmHxjskqkVufrLJsiUnODrlc=,tag:KkASDipOAGfD3sKwvHv+FA==,type:str]
    #ENC[AES256_GCM,data:uz47ypCwBrD3SEI67Q==,iv:sGmiRbcJCeC5wOD0SotOkCZDYOmqM4IgPCTNUSoWdOo=,tag:lN/An2s+zSXk8fYAdbQiNA==,type:comment]
    TEMPO_S3_ACCESS_KEY: ENC[AES256_GCM,data:5RAYfh12CJHWygRYxnI3UPabsyQ=,iv:tPeFx5UAtPD+p82t0Mvo1SWemUv4eEGDF3V3BTr9Rss=,tag:mNEnQedFcDXdlnO9viOrxQ==,type:str]
    TEMPO_S3_SECRET_KEY: ENC[AES256_GCM,data:OafaAZVpYcEIkehhS2i/x8R9h59H+tzXVu9lj93HBvQn6+pA07l89A==,iv:xZ5vBLTelcsxutY2LfNqOJ2LDYS/KnrRIGDp1ySJZhQ=,tag:pu4gqGKjh+BsovypjnRSYg==,type:str]
    #ENC[AES256_GCM,data:jP0WcK3VrwjbF9zZe1o=,iv:qgq93zqJgl9BrI/VP35iIG8wVbB20ddVk75nSh+NVes=,tag:ykqSSb4gihe5deyOXp4vaA==,type:comment]
    THANOS_ACCESS_KEY_ID: ENC[AES256_GCM,data:9ezzkW1Wgmy5vJnAeN0XdtqgAV4=,iv:vKsQNcsrEFkMWPA/stuMDxidHXzYYu6t2M6aoI2xwPo=,tag:sFqSCi7q+DRLHbtxPyOIOg==,type:str]
    THANOS_ACCESS_SECRET_KEY: ENC[AES256_GCM,data:MOLUcfDhAyFcN7388cT7uY+3s8FK3TDe8cuVuj4xVXbl6ghtbk7zNQ==,iv:OaR/NCmK+5ZMjctsR6W4UsDoxPgypRaY2HVv+os3d4E=,tag:X+ncagwAleVkGfNbTGv7ag==,type:str]
    #ENC[AES256_GCM,data:BK8obDvrfdzbErN1yAQB,iv:BcjaPWVcaP9NHlIbpuey+h7luVpXZc9aJDeHJgL9VMo=,tag:xLXYWASFw/4/LIOo/GhVHQ==,type:comment]
    GRAFANA_ADMIN_USER: ENC[AES256_GCM,data:HiouMjw=,iv:S0o+jDUibDJVMcPIHDyeAhOY6EzaBKqUglejsIQ7ih4=,tag:s7aFUMQxO/2KbjeD85X80Q==,type:str]
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:ariMWgT6Se7tz7JgZAax2zMxJnHTvOasjtSf9EC8QGrN8wrWXnGgsJoqlg==,iv:Wz52WL6LR2FtbSyY+I1d0q3rhl0KwW4rysfVtfBtSZc=,tag:CNptjNu4rvHYB/SKeWslVw==,type:str]
    GRAFANA_AUTH_CLIENT_ID: null
    GRAFANA_AUTH_CLIENT_SECRET: null
    #ENC[AES256_GCM,data:Ph7AmpsDfevXJ4slEnRh6dHQUlUPlzs=,iv:vsFANt1uwD8zrCD5M2p5K99XsqmboqI9HWcXGR3Gpvg=,tag:CVpERG2ovn9s/vRzZ8VmSA==,type:comment]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:nxZ+ibON7NmPw7AGla1r5i8POCGuXDAeXsqAOQRWOXn3CZqJ9OK1I8kThq2kUQ==,iv:lPzPRE6B8cjMxvvT6hP6/OKolSCyBI7hZLW4qpwqyEw=,tag:LsP3EFfeXEZGgZzVJL1Hxg==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:w0AXlYX5ZgClUfs=,iv:3LlXFETMarID+pE38SOSAzqsdFO+lBvwLZMiXIiCKvg=,tag:5+dVWtaNy4cAPYXgLDf6Qg==,type:str]
sops:
    lastmodified: "2026-03-04T09:24:11Z"
    mac: ENC[AES256_GCM,data:AF14/uFfJqt0imgAIv2C+tURERUDSiLpINpQxpOXtN3DA2HoYyhmxska4bG/VyEG0mHVKigxzDnqCv6w/GpnIMBcb3UtMBvwbcIfYaey3qZehuPuJLG8CZZpydmQE2kNzo5Jw/4YwFxQJ7oGv9yk08pZRe7PhQLGPqTmEbICrG8=,iv:H203AA9aX26c/E2qn7YFolhy3v3Is6VY7cgOY3Clprc=,tag:xw/hC2Yw8r9IwXHzdT3yvA==,type:str]
    pgp:
        - created_at: "2026-03-04T09:24:11Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3McSkAh3rFhAQ//bf4ugxTWOFXkRvhexm4pSFNrQoCeb3Dz3V92ij8/2I+5
            lNVsipZeiY01AvxqumH+lbJ/l0Ogucd3CrYHrb0gXVvXI3P5KwbQVcaNFSohXk9M
            YMaMCy+vUS1FCz3TPVtcMQXyMO6qTaWsZgPhivARDRq48y7NJpZzbffDJFD8+ofp
            k8NPJGcHqHsCQSin0ytgE9aX37ICgnV8WXjdchsmfplP7mVtfAfqkwkInuWlpHen
            Wquw1yWD0Um9jQkQgCGvkduvIoNQj+v109SlNqRQKmFnSEFVP8dC7W7WBk0au7zW
            CtQF/Vmm0bL9szW2nzbtRWiV5dj7buS1s8P+IcUnTqKBWO3roFR05YcI0m2HAzjD
            sJnbNM54HemebEityXIkucHyo0jqJ3eioOLDddAzS4XkRfO8iOaJ8sHPVWXv/S4W
            YKezv0ecrFAzkar6Zpl0ghFpIWAe0i9K8qZDvn8d222jpCJhjgZ+HzpH/oZVBj/9
            1/dH0CHEKmuxa8otM4YgDw9KhIF1l3ciCW6y4lFH85Olc84H48U7es/lX2GBk3rG
            9ykJ57e8a0vJ87LTWHbOqWpkbRPhJGO4G6wRZNNsc6DL2WEGNxgskgKwnaHiaI9Y
            Q9RuKQfEJcwsHVrdqy/Fs4jsbjmu2RZvA7WccoylSqkEampYghCUNO2hEpJLQJzU
            ZgEJAhBhu1S5R+a9cH/T74nYB1C2n2Xj8irYdy6WLf2l+HKvAam9p/JD/bDZ+ain
            gD38VXRQVUymiI83SkrNnFBs48QOmjML8jJtyNx5Ybg7NlPYptxfItJVw0WKEQDr
            IgknBTkbkw==
            =GZP5
            -----END PGP MESSAGE-----
          fp: EF552EBA773641B396D26658E1F56350C447581E
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
