
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
  labels:
    app.kubernetes.io/part-of: istio
spec:
  releaseName: base
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      version: "${ISTIO_VERSION}"
      chart: base
      sourceRef:
        kind: HelmRepository
        name: istio
  interval: 1h0m0s
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
  labels:
    app.kubernetes.io/part-of: istio
spec:
  releaseName: istiod
  dependsOn:
    - name: istio-base
  chart:
    spec:
      version: "${ISTIO_VERSION}"
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio
  interval: 1h0m0s
  valuesFrom:
    - kind: ConfigMap
      name: istio-system-values
