apiVersion: v1
kind: Secret
metadata:
    name: kube-manager-secrets
    namespace: flux-system
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:PlC9KPhZukdqUY3EfTwSHFQ8zNR4LXnyXcxo//FgSYdcCL+A3BsFFeqZgntIF4VcRcY2V6d8dco+i/60byn1sjkT2POQBhsMaFBPmNV0leou9fzsZVpRXJwXwqccnBeIfdJBtQBytPgMnxryfbQPleBfASZ8zV5naUBLEShXZlR/TywQt0J3PWPGqDA09Nkfp9+3dVu7TKOK+ZmZQVqT/FCqmMhZblTEVlz2FkT+OHSP9l0BP7sJJc3BbhsziKB7zdVOnGv83yjwDXZ6g/XazVSWmtMzx/pVJqNpfQan9eNd4xCZTcDt/fd5Yp6tC0GGnz9uh9VP9846yffy+Q0CpQKI5ulyUxINJWAl4WIOr+v36WuMmfUxKnitN8wABOxVG2fTBpaMyCfFoTrjLTXIGWdnfpNaQ1djTHvDOTRuTKeoS8WdI0LxUBlWUgTuD6IQi5php5sbEGorcolUruivl2rGQbnMrxATegU/WERlCGP65ZbHBoedltImsL6G/HFE9fMoJyC+4BQmPJ5ojbIrw7DRtiqLjbUrcVqFtr1vstmDT9EGENpnWc1tkoUt6GUEaXSq3yS3DYI8Dgvb14yz6j9gOKsbeyXLyjP2Ly0cbztZiof9np6bVRt5MSYNRtQM/vTVUrK+UjE=,iv:cK+xH9ST/YEX59GFcMJniHocFhWFx+YKWsGtuFiAvZs=,tag:e9QxcNL3dtuZvbG/2tg84w==,type:str]
sops:
    lastmodified: "2026-03-04T17:59:48Z"
    mac: ENC[AES256_GCM,data:h4w7UsHsKhKnibphGEB40WX4PMIxJmHxGQQOQf2+hWH0I7C0WRUNGm1WndIfejHWNqVqOUYjJXnoIhTm4r4Usw6IK3nFXF79MN+kjNVdmr62lV0mv8ZF/es97QaL8/MUd4Dsbl8ZSNPkWs+GfBUeT/f+Hom0dKlypyYU7nPE1rA=,iv:mDV0exxSarJlXdD9UUcyXqmCwE0WVyyYAoNXbcYFEts=,tag:jhNrvTI+jgNpII2a57C9kg==,type:str]
    pgp:
        - created_at: "2026-03-04T17:59:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3McSkAh3rFhAQ/7B3fOJgOt8zsx8y6WWJ68AVKcqjI1yjdWuJlc3dvwPwYo
            sLiPap6bJ1uavp3i4rGSCF5XwDkbNx+LoLczdXK3jV4dhw5ePQaLHT0HBIlhAUgP
            dDza9IPUaN9fTIeZzT3dIum6vjuXC8ykcEqz5d5XBAZlgZmyZoYFA2kZXtoNhAV6
            nWAdI+1TKPEVzB9acmtZXXHSOauc9EXWJbduvQThomQMlJpcUj6DL4szZf3hidOM
            Ovksxc1ELSv/t+7b1z29CZNWNoQ2Wwo040hGbPGiKrRAZ32Xa9hpuGzVsZdVrKZX
            pqHOvWOkRC1Clc4KjaQFi7/yDE7aQqqnzB0eJyEZUbxFdi53ubmoA99z4qsR7yQ8
            XeCSxkjZyp/5ewM3+Jlnv+23Dja4o6Aef6ETjVkNSPvh3/oLUL8nOCZKVgDbKTaD
            0vhbk4yIqMc+WUHCv6qWLYc4voqAqQCutBuMcJSnMFGGCulEcPFqSNTJ5Qn1hfhD
            RLmWe6SEvDkvGasruis9MEEVk93PcyghUlfjZuUDzAldPiBjbgoItCQUh0YEX2Ee
            VWwM+tSKPKrCvYaevFLvuGqXRnYfqglUsHW96xbb4keBbEgK5v9npUY3M+ruQoDd
            mcHGHZAZ4CQFf4U8y2SHLOSTnSoCa6JpM6F1CM95wOagzhvdPE/GoKQvafrie6vU
            aAEJAhD47VGyhRdwShysiKFKXpWAYiMM8mI0m1OilcUBsBEymhCjPFKpjglmlSMg
            F5UCV4et4UyUEM5XgVQ7uiH1rsqiRz+JSrBbRF7yRpDyY8hB1hcDSIJX4gUOJ3L+
            /vGJqdFvVW8q
            =QSJh
            -----END PGP MESSAGE-----
          fp: EF552EBA773641B396D26658E1F56350C447581E
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
