apiVersion: v1
kind: Secret
metadata:
    name: kube-manager-secrets
    namespace: flux-system
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:u+e+jXibU0xSwQRsKB9y51ZEfLB1ecW2NX2RI6VxKH0RWjJRkeHQhdgueKTp7kYV0RWKYl6ehhNthvRCEqkJX9czBc6G4KBt+gJeHs8+bCwufOi1eIvxrG0tyc7rAac8Od05FPdDhRdssZOrt3/zXExeJ2npoWXQkJ6AntF217EwkRzjZkBTlyELRR5Gl9aotRrbKrO+DRCH1Y8XhS08s7MD6lCwKE59UTkPci4wCXbEBbJ+4EH6dQWqfX4CoVxZmYZTV78oCdB3cMXKSmcPhSwlczUzDgMFCTfI4D+cEhqgvA7zqQZaI0NcGelhdxhd1TxHqcUjYZvkF7wytmXQ1XmJqN5/O4xxbULpHcMlWLCtvBuUoNjPyVxekrUthRPZ9+aowQ==,iv:9RiRmLndRnd/h8369gFrx12PbK8RzMsgpdFVpfqWBSw=,tag:CFXhOi3ibV15TljNxQ2+AQ==,type:str]
sops:
    lastmodified: "2026-06-01T10:37:01Z"
    mac: ENC[AES256_GCM,data:ZiJJAZbGVEvQarqeQzNKCDvbSTsIPWTmwgLEEnUy+hIl++MeVWYnCxaggtcXYVzXEFpkfnwrg0jzRHbpce9iN4FBylvavotqe6ykj2VbW/ZEFZwXhQRiqf23ZpWD5ywY0C1az2xHkja7eTIrj75diE3Pz/nB97ZogAGgyz1pn4I=,iv:De/B9o9HWHin2L2F3FdhfYAoilWrzunDJ2tcLhIOfLk=,tag:5k/U2Tpl8Ss3QPhdNZ98XA==,type:str]
    pgp:
        - created_at: "2026-06-01T10:37:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3McSkAh3rFhARAAiGP0JuneyrBWxJipP831hgQ4PWtAL9juCizhEqKP/L9J
            AtwH4qWez5bOjGdoHBNzNowrx/s9wa7H+VHL1nz19FSTnrlMG4Gd9A1qqdEHbXgI
            p9NE1BlEOsFvlqUzuSgKj/SzkLI9lAstYJtJhgNIK8ccPc5byqUJIwqP/ybCeisg
            Q9xW/yBZTSfwBFxTkRBFP497qAutMIGCpP9EyjCb73mOP7G+VDU1gXhG+UIC2Wn2
            843NgmmHd3r3oRmAgAq5HlPjIGZP2v8UiErsvyMXKBLyJRPMb3DIZT1LTSxgVuiC
            fhrcFYNYi4Az+0AKmG1t0E0Q7juwtb8/YurLESySfAz/x8P+eOIo3WJ/KtMxSKSo
            UlOlpQBD9hafceyzvWF9u60zHmqyNxiSxrfgdC7bV9/9my5oZuyU81cgdfcPegbA
            sO7+F6dYqre62XLoxLpEB2duZBxTqF3gmIT0SDtQhiKmTvPMgQhSLBCm3fy2WJT8
            9Po6DSpu1ZstBShAiVqMqxD19VFY5rg3WHBujAcvqU0nkoXBD6zUpubKs4jN4ppb
            zc1RGQ4/BdkVyvSs1biXDoj3vgZrP74whHLagmhY8GXzSvcvIlPN0E8HG1a2K1Yl
            vXswiT4GdJA2Xz8z4EHJPxMo0sdwlwCyWVHDHwbJN/A9HNt440xUI/sNjg4l24TU
            aAEJAhBZnMe8tcrmApFA0ecUMyvFI1ZhmsHYmP9hko4nxowA/VZoFf1A4gUULn2n
            Mi5kcsgos6PJNolh4XkO2oNDowNqncyKc7dLZu3Ou5E96HAS5zhRsRLWzkh2OWVT
            i7RwU2/Xj93s
            =UUJu
            -----END PGP MESSAGE-----
          fp: EF552EBA773641B396D26658E1F56350C447581E
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
