apiVersion: v1
kind: Secret
metadata:
    name: kube-manager-secrets
    namespace: flux-system
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:/iwqJyLp88orRruzZPTmUiqqfS1YONbJ6tmBhvVGMk7fbVAHv4WxdKExnVyngQJR4Q1vNignEM6f78W9CgRCIu840HpLPN/vhKF6nwP0Z/q0W7AfSDHJEh7FzQ7xzczVm3va2C7Pn/8j4EWNKSzcXz2vfP2h0yK9VdFwFiyM7zxHygG6PJY0TRUujF6rQ5ykUMNjndB+l3pRVxGSLRr2qSETfU9Jiu45Ji/NURR+xM0J7ZUJLOlj0ibCzJ54IQySEC0OjXVSiwk8B5G6uYtA5aP+8ugWdTHSCMTQcmMC30YjlifrgIn/qdLVimoI6PXuTX47tOoAgidTfZulzR6+s1Gx6Ju6svbXC6K65hYqDbbgGzQdMvrFJ/a0ND3/w8t5CZaTbCAxOrvlqFJNqIA6xmngIMj0duZ8C+3apoE4EpBdPD20Ezahsjm2vZQH+bbAJG4YTBrM2Ezcn78/ny1dbGDatANlAL17YMigHx++qTV5krkiDbVl56j3YMt3ykCo2PsMNt/cZZ1jm0pQocHHCHQ7z5sF8dk2ULRu9Q+KgZ6CTJORoHee1e1cLpdHygZNlYDLILHJq2mCwo83cXIVaaAc4A0UbXSN4cytGZ/vzNfhI4fTbnb5j5JXiyKg3lRRLToXYx9s9LcK2BCEgWo=,iv:1gwoiLw3o3adJb4KOf0QgZfgqUyE31qPxY4/+qXkSCg=,tag:JjVuZ1i+39X4aG0fGrsYfQ==,type:str]
sops:
    lastmodified: "2026-05-19T13:43:32Z"
    mac: ENC[AES256_GCM,data:SV5DKWCnxB6jcuoVI+gIiCFb0TfXa+Z+w8U9ch1Sfc3m1HAY7X4tqAMrSDsTcrpsdwyPBwizV5C2lSPrldhqAV0qxLsWYi+SFRkAkaP13oCY/+R+CRm3VJWn9CWNR8sV15cXYlQIQwxqPedlQ4FJ/3B1BU3HFf0ZBHCVVGRwLZU=,iv:+ieNd6xNldvHxJsJhUW6nArjQxCVsrWr8ockw//TFaM=,tag:wX0vEVcxQ0hnmqTSD1wEZg==,type:str]
    pgp:
        - created_at: "2026-05-19T13:43:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3McSkAh3rFhARAAryK2gG/HuArGKkN7cPqVPDVwx11ApAEs+UBY3VlaCWKE
            AXumfuCEBbuOxBGrgnmhul0iHEvDLYAnaxNrtib3/CtT9vdN0hmhpAaE5rFhI4Wo
            yC0aqSu7nC6xZHrKtaMnkQrPsm0uCXw95sVTI6Hr7E1S3E1h/t61nk7xduq5sX7K
            GhefysBP1ZzQnWOo51Pp1xS4I0Q4VC/fIcaWs9E73aQi7qxWhEUYvhks5dj82ko3
            9YRSbYxmL8fQdYZGw3rZghcFzE3qMkBkJg7mjsUSteT0BxcO+S2y72G1nHbkht7l
            QJD2r/PslKnqDSzKhOCG8Cfs+7cWBP8591ElHIZyXbhZJBPYq6RbCr6xn1WXNsb2
            oH98SyCsyH/ma+qE+M8i+eF7euAeXWocVB63gqfVlrr9VQsdIIRzL0dSteJ3y7IF
            CLc6jGL3SaYkzOcl5jP2qT7yOnpZK8387/022jZm9RYZ0rQ8PSYqGuXO1mAqBcMW
            NaGgR6lOmXD95Z0HrAXNarDlObzZb2Sdrfs1fCXF++ufgxhrnO4gS7s/oRy6mtKd
            6RS6Xgu1zQCp9KHaGWqdfV/dvdyeTr6wXLU+LHKmr/BdULn7pBrmSxj4Eqj0eB9X
            8iNsGCkYfU3d/UBVIK/2Ou9HIDhE7JC0JBFRjkGU5DYUy+OpYIQ0bE93LR6o9AbU
            aAEJAhCSPqqZjXSOd2UGv66N/ccIl1OPi4l9eXcIALi2o2QtvcH7HpFhn+9zT3Fo
            irVzWcwfHYd5am+JixXwqm9EgmQWhRQbYvMxlBRIpI4CaxSUYq1bAeiFl6b1droX
            M6ZXPsgw5XLC
            =M7LO
            -----END PGP MESSAGE-----
          fp: EF552EBA773641B396D26658E1F56350C447581E
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
