apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-ingress
  labels:
    app.kubernetes.io/part-of: istio
spec:
  releaseName: istio-ingress
  install:
    disableSchemaValidation: true
  upgrade:
    disableSchemaValidation: true
  chart:
    spec:
      version: "${ISTIO_VERSION}"
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
  interval: 1h0m0s
  valuesFrom:
    - kind: ConfigMap
      name: istio-ingress-values
