autoscaling:
  enabled: true
  minReplicas: 2
resources:
  requests:
    cpu: 10m
    memory: 128Mi
service:
  type: "${service:=LoadBalancer}"
  loadBalancerSourceRanges:
  - 91.211.91.3/32  # dev
  - 2.59.222.79/32 # ua
  - 91.211.91.148/32  # pl
  - 91.211.89.45/32 # nl
  - 92.118.205.208/32 # ocp vpn
  - 91.211.90.178/32 # ocp vpn
  - 46.4.20.147/32  # Vlad
  - 143.47.228.252/32  # Vlad
