apiVersion: v1
kind: ConfigMap
metadata:
    name: environment-secrets
    namespace: flux-system
    annotations:
        kustomize.toolkit.fluxcd.io/ssa: merge
data:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:Y6xIYZeGYPYKpy3/gB4hVxnG5ZiDCO4i4PS8yiDZtQlv/NWUv80EpA==,iv:U7RfQsv2/X45ySYx6MWZQGtHsww0Vx1lKKZ8DZ7EexM=,tag:tyWryp+5MomQkiNB5Sxclg==,type:str]
    VALKEY_PASSWORD: ENC[AES256_GCM,data:QspqYYSAUfaiMVocxO4Ib/tGRKwk1g==,iv:S8tdZirlEqOPwPrE8w+a02tBxTvi6nOZn3kK7RIAyqU=,tag:rfHFs1jSW7ipFmRr0iNNHA==,type:str]
    GRAFANA_ADMIN_USER: ENC[AES256_GCM,data:9+IKVLQ=,iv:Jb5SqYFvylzTs004kaSAj/HPEOfEiklwK+SUc/OvHfs=,tag:+9xBjBAfUKyHMRlJqEpMBQ==,type:str]
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:8dnWa7nA8eQqnSBgSExZWmvZ9f34eA==,iv:nCZPa8FUuBvb7b28MGJrij+8pTq6Z2o+KAJoEcCPoyA=,tag:YGECutzzYHyYJbLr+ZWcOQ==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:KzOVlZB6,iv:t1k6TmKZhkttH+xkYZV79XVkLY2i+XzZdsyo8WDea34=,tag:/iPfoNlvDZm3Rf+MnkHvlw==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:QknocUA1,iv:tG6i5Y60lQJ1D71HLTr28RWQ7FQOKMirRCOxCTY1urY=,tag:bgqCVwMG+T35tJDk97Alcw==,type:str]
    KIALI_SIGNING_KEY: ENC[AES256_GCM,data:vm4fG4OfSkjflywNlbYr1BIgYpIAaQ==,iv:283FH0ZwAKmmTlr4Yu6Ut5PmBRnFhm0y8ntkKF8roOY=,tag:t4eZYRziRAgT1UKGWnumUg==,type:str]
    CNPG_ACCESS_KEY_ID: ENC[AES256_GCM,data:OY7aqFOElWstIhJB30Gk/iIMU6U=,iv:PHdXcpfOx17RlEtIPeOgBxqdrhNPdCCEzQPM6v+XL0s=,tag:odTW6SMM8Pw09oX0+0w7KQ==,type:str]
    CNPG_ACCESS_SECRET_KEY: ENC[AES256_GCM,data:oYm65MT8eM8urfJOxYcJSW7HwsdjjW5k390vYJEhcYgaxRRm6HDd6A==,iv:wzXfBl7fHgV9Lttq6ekFWkN1V1Jm+cQbNBgtZMDKRiI=,tag:bvWh1bjDeEIg6wKxLD7GsA==,type:str]
sops:
    lastmodified: "2026-01-19T14:32:29Z"
    mac: ENC[AES256_GCM,data:BQ+gI4mP3YfCGuSl0i0sCai4Unz25GC6kIoVmcyTQ7AxENQ7p8NdVz+DLlybc5YT5mr/Duohp5B9Z1CHAq/3WkdcxsWUqXGCwlnX3knISlfNYRrYrdee/TDULvK0FcMnc8CoZJUXRNZJu6DRI15prpkAerT2W5WB1QGTf2vWi2M=,iv:byB8A6lJ2TK0nMXkWXBoa44wwJ4A48EOOBmHnFelb5Q=,tag:xj2gK4aF+eRB9DB0l9ZRRw==,type:str]
    pgp:
        - created_at: "2026-01-19T14:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3McSkAh3rFhAQ//S2/kbqrNAn0tDZlMLheLtCtzbBucAHNl1vNCinTgrOF3
            B4srkeY6CCD4T7Qw0GQ8LjN1tNAIDbQr+SatjjpkfxXNbKifzxNaqUmG4X0KGJVG
            EyGpruGCtHcGGBOZvPfv553ztHGPuTG5Iq9a68TBKfHSbGkOeegU/urF2fBWxvK1
            8uwRFQKzCv8FYTMQEygYoEn5hZZKlqqCrTJSCAofvw5Jjl8GPjwMsITGfAQWpiBy
            bVrk+gmk623GmnScjtVt6VYoVvzV8tC4F0m84j9UF6pipRi2GpcpKHarf0OA/jj7
            OhejqurDtM55ONDWAsRUlBVtuRROIRnio5LVzjXE6fwxhd2kM1awNasqZT4bN8Xr
            roV0N+tgPJ4CtEStVpLBUgq2DGN60MNo4gVzQCWMtubhUXqJpXhr8IQjb1n3jCEQ
            R2Id29okgoSe5M3XVG1ip27HVJF57Qh32bz+haZv6uT+PTEJdcnlRr0V6F1hl0in
            fsaHDKOxyLXMiUVvFGjymBtV4F2yOpx9xtDsvkcTbn/jRqFA1UWAF4QqzM8+UALL
            9HNtUVYtF3Yshc1RUZIccxhxkiHA1p9suIaB2zOb28ig474XeXOdxRmuI1azeYjJ
            kVjIYC+GOD6D9kk3PjSm6iBJmg9s+yOG/EOpXOcgkwxMpuvgkxy1nax/wqDSrj3U
            ZgEJAhD4CtTOTl9VgCthywEcAomDHVl9NjfrFnp1QJAz1/qD1EnB72woT96Wipq1
            Z+kvZkOst46++DaTWeklgwD2iRZhomwBk+3FkqAREnqoH1rubgJplJUiRVuzF2F4
            aMNA9KJ6RA==
            =PPT8
            -----END PGP MESSAGE-----
          fp: EF552EBA773641B396D26658E1F56350C447581E
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
