apiVersion: v1
kind: ConfigMap
metadata:
    name: environment-secrets
    namespace: flux-system
    annotations:
        kustomize.toolkit.fluxcd.io/ssa: merge
data:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:FnWsUVsIvC4=,iv:lq9n5yWDQ+dIUotEAjLdb08hDkGONbISuPDTijNm950=,tag:865b21oGEQ4yMmyGr/mskA==,type:str]
    VALKEY_PASSWORD: ENC[AES256_GCM,data:tRZ2DDfTac4pLHkeZ6iRY1sauen7hQ==,iv:8Qaeu6AhJewbNboVgN20Wd/nMznzTGOg5efGQSekt8E=,tag:9zdBD/tEffIyKOvzQWY+wg==,type:str]
    GRAFANA_ADMIN_USER: ENC[AES256_GCM,data:Zfq1ckk=,iv:so8c433Dc/AnYYkbcCEC/ef6NxuIJvrRj6/Bd37zwRk=,tag:B6Mb9d8sy4HPIt15u0PFjQ==,type:str]
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:NvQrWJErfKG63xSb432ubyEJsRATUQ==,iv:PT+HITa4lGSv+xiuPwtnA8PYgshPgANWt4XSmHDTIBU=,tag:ChK35bZysQI6tQ4TQ13zug==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:3kv7tBgD,iv:DFopMHBYV8xmIbYYALNU7pPC7V5WKYBi4+DO9Q9R7LM=,tag:ajxvTxmRNL0m+laW9Bb4fg==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:gBQZ8urJ,iv:ePN1iHoy0wJS7OuPZXKd+qmzsCUlEdQYLsn7W9tTP/s=,tag:CeoD9+TPKdQxVTq1rKVWYA==,type:str]
    KIALI_SIGNING_KEY: ENC[AES256_GCM,data:J70lCrsbzvgjVeJu24G2qChIoOlVTw==,iv:c+iwtCfkIKxmhfPRZgsnV5+REis8MyOvgb1WdRyln0k=,tag:9yGMSPFGKR9Z2tXAWvuw1Q==,type:str]
    CNPG_ACCESS_KEY_ID: ENC[AES256_GCM,data:LzvT0xZEU27L9BzkSdl1UoT/NSY=,iv:dq+mGEED3tflC3ArSC5jQocT9yRyMH1tXQO8Tu4lK8o=,tag:pUObW0h+Iyw/KbNreNA5Rg==,type:str]
    CNPG_ACCESS_SECRET_KEY: ENC[AES256_GCM,data:ya4ImkXgYNbZWNuZB1AokchWXXevP8je3QmUWSumeyR1XWHgdFpLOw==,iv:ugOvg9Zrdu/Wypdr2q6k64UfKl4D7J5l0jefUGfMc0A=,tag:kmxKhcTgOWiB1XfQVgtugQ==,type:str]
sops:
    lastmodified: "2026-01-13T14:56:25Z"
    mac: ENC[AES256_GCM,data:FQ6/7WLbgKECtXmpkfTWyqcvcSGoRrKwZ3Wi4RDJAULtz0v5yowd9OTClE0cs6HME3p7blB8QfrVhBiEKNw1b3FNI/eOez/3GX6UBPkuISbkEtcLEswFZL7dBHcLNOs/Zs/y8KlBervNL7pt1E5fpE0odfeeKWCruLveD3Yh9MM=,iv:AnPWyvfdgEuEHKXkEH9K/9haboiIiBphskDIZh1DeOI=,tag:BkOzQ5bD/dVvekypdUrenA==,type:str]
    pgp:
        - created_at: "2026-01-13T14:56:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3McSkAh3rFhARAAgXnsgzHgSq5BZ5yYXTOoH4iEDF3+qjYCJGu9oNatt6E5
            xAdbj5YtULd2VM6MDvgRoGSX71nGy/Y3bXEDI2BvqTkK4fyAOXIQtuVH0Sd1IWt6
            qLG37KdPPB/0A5hX01iV2mhM3BDDY5wlBi5bPtDGzaODMmEFbJxnFVj+a9PaHlTa
            3VscHaQ40n0Pioy/5xXO7Up0idrdTpKqQ/YjlsggP33goNMGWl2tedbN8ZV/5f0t
            gDDzkw4TDKET6DlLk/mZeHXSUEPN0bYxuqKzfh8vviV7rm2vtkPVgF+KoRyurjuU
            lKzYhjkWVNSJF3LbPNqd5Eqn9jG8XdhLIWP1YeqLXJuakT5eVtxsjA9gzcmoGRqf
            Z5nxYfyJKNdwQ3WcjgX1OYK+2TqmLtpr5xC8GArzNGv1k/wKaszlGrXkzcZUJSGV
            4kvc+Uasa41V+06ZL84sShmdXJw/TpFjGAFgr1zNNWwv+JBc33Y1NcnOYPjXHUpu
            Mg7mryhxTMCLH69kNcSCRbk7fI0nmtMbBBpeiOGFOmmJyc/cMyvybodvxZIMEMvT
            9y7Ir6yLKYyZ9Y60vlR5sD9TYpSbvPL4lDC6w7Zv3ZQUGA133ZNffxEx0rztEroR
            AW3xNBSBkjcYKWgDVhPKBCG/ugP4JLeqBWsboAY9oB60VtfOY623rO6sMVZkoNzU
            aAEJAhD04cWFbz5GVcHdLsdd7A7sdzYrylncDUxcxx/Qd3HQukT3cMQ9u/tj/JYf
            vut4BDVBaUAx3veBxUyd+9zQceJla8As8Txeae0XtzDdzBn77xVoKjJ2Sx8iNrGD
            dLGrjlgl1Z2v
            =YyJg
            -----END PGP MESSAGE-----
          fp: EF552EBA773641B396D26658E1F56350C447581E
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
