apiVersion: v1
kind: ConfigMap
metadata:
    name: environment-secrets
    namespace: flux-system
    annotations:
        kustomize.toolkit.fluxcd.io/ssa: merge
data:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:ALZKtx/grXUYJtPQXkt7SiFkI1h9QHgEj3k1pzMAqw37iXYCwloP/w==,iv:LhbdJg6VPEASGXzWbdNROVj6D301KlUMuLBDHrQBQUo=,tag:eegIHF+1hWRUA5sLgRIQNA==,type:str]
    VALKEY_PASSWORD: ENC[AES256_GCM,data:7vM1Nhq56vEazdmgxsAbKSljdHJdXQ==,iv:ELGIJzMP26cRj6fclAP/pkUDnZynoqnOa1jo+v9a1/A=,tag:zFWeHJLsykeWcuvYefMBmA==,type:str]
    KIALI_SIGNING_KEY: ENC[AES256_GCM,data:zpyUdTWYqfQYSqI2KS4VDVyqOXy9Ng==,iv:gXZ8obh4lI4z7Ro+0nOjQirn9CY0GW5ZUqgJDv6BneI=,tag:RyKULgwb4xkgcNZg3mAPVg==,type:str]
    #ENC[AES256_GCM,data:xGGdxDt2Irpt7g==,iv:ICosS/NBaK6V4enb/wws/J3/9f5AotKwX111Ehtn//M=,tag:dYvw+k56kZmGJrNDPbJT0A==,type:comment]
    DATABASE_USERNAME: ENC[AES256_GCM,data:BdbZ+/3vSGI=,iv:c9EEWQVliosNQZCG8vRikL+5tGCPU88dddFF0Y3Gk8A=,tag:CXju/utFBtD60VoRlllkAA==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:yDb+XSTYwoGETkdhZ/C2jQ==,iv:vzQ8EIBO48IuVKIoA+X+ZP0e9hzV6nu2YIjFfRdkJj0=,tag:T5/43vfgGsO5TbtF7/HgqQ==,type:str]
    #ENC[AES256_GCM,data:qBzI4pcIEmkilloGfAX1+An6,iv:gH9TsAVK/5Gmh49ffNYjp4UTVZtY9xTwGou63byL724=,tag:vxKTVye11u/fjbPk+NQCzw==,type:comment]
    CNPG_ACCESS_KEY_ID: ENC[AES256_GCM,data:2KGDe5m7IBwNdpVCCP8auycWFfQ=,iv:0FM965H90tPsvRHYGnF2UiQ9GM/2h/izcNNH/wEKvxM=,tag:H+DVlpTc0ztiU3O5bShcqA==,type:str]
    CNPG_ACCESS_SECRET_KEY: ENC[AES256_GCM,data:MyrTXfAvOheh53QWcXg2NravlzqJXBoUEJCFRmbrPjklr8G400WCNA==,iv:H79FD4S1MOLX6bAEwFtYzNLLlwKBTQpxIe5pZ0woQsA=,tag:U/sjaTiKRvI+HG1tgedu1A==,type:str]
    #ENC[AES256_GCM,data:WisbrHdE8XkkmsUC,iv:kj4Ssk3snRyyDwbjU26OX3IVU+u+A5KvP52MsN/cIpA=,tag:Fj4VdbUuMR8X+HN0rtnBdw==,type:comment]
    LOKI_ACCESS_KEY_ID: ENC[AES256_GCM,data:pcNDBelJbMv+L7E3ddCPDvkp2qo=,iv:mD0awspWNeEnKxti8TeGHh5/zNS1FLBR8FvlbExYP2A=,tag:ShJys140nBwT3K7Gnhdkdg==,type:str]
    LOKI_ACCESS_SECRET_KEY: ENC[AES256_GCM,data:KsVpkA1YarsQHOZb8UwSjzI1luejJXOCePsBHQUkHxG/hfICNuU8BA==,iv:IPyRy1hETpsp7sNrxfYqyh77bRPj8YyXX59w022S/hs=,tag:NK7Y6XX7SaaZIU6bHh9/OA==,type:str]
    #ENC[AES256_GCM,data:EzD1gy/kuvA9AwTclA==,iv:CFsMAdkAAGie09CBXo3Ieng9yRcNE59BFP7drIJ0usQ=,tag:j7i+fwjGl0Q9OwX+1Kg3Mg==,type:comment]
    TEMPO_S3_ACCESS_KEY: ENC[AES256_GCM,data:fUhr6DCQopFjHZFrVv79GyoTYio=,iv:SIdWVVHwFVWu7h3cvIzhRAAaRa/NJ2mjn0WpF5+dafY=,tag:WXlryPF9KIYuwuRm5/Fc0A==,type:str]
    TEMPO_S3_SECRET_KEY: ENC[AES256_GCM,data:Fzu/YomZOVq1eJx9URDyTMFcGF5l8GqLXrbFiVSqQT/PQ5Y21fCXsw==,iv:9pCzjFg19+IWIRuHNw6ZqbbvBjPoURH2VLkri5+Xbf8=,tag:6rl4N3pBm0Ei38Fe4sBJWg==,type:str]
    #ENC[AES256_GCM,data:Z5cv3oZzF5t0MicL57w=,iv:ziOLd1BpyoFFyrWoBs8duyKQR3T+I9BcOvfjNsJON/8=,tag:2jlJjo65XVctMFUWYhmY+g==,type:comment]
    THANOS_ACCESS_KEY_ID: ENC[AES256_GCM,data:qu5niCQYbyCdIlld+NBj/R+ORBw=,iv:1OyWHSg1+HuZ1TbmLKfeCW16Cn7zrVXEJP1wVsK17Yo=,tag:IHZpAq+TAA4wPMU0VqJWBw==,type:str]
    THANOS_ACCESS_SECRET_KEY: ENC[AES256_GCM,data:lbAE5cr55oI1yr/kclFuc3NFPeuesiKAh/8lLKQXvKc6WroL6YYJdA==,iv:5ZsrIbFN7LEKwZx52X2dcNkvqossJCR6+/Ultmh9w7I=,tag:uPqXYQCONUoOF2Bt8/mt4A==,type:str]
    #ENC[AES256_GCM,data:ZbVIuKJTUDctf3mCHoIG,iv:h8IVYP5M5EsI5CbLnr8tEl4nGfwBXhnimywVWLPUXyk=,tag:ApSwUq3yLRIqqF6pSp8JZg==,type:comment]
    GRAFANA_ADMIN_USER: ENC[AES256_GCM,data:QEtF5b4=,iv:vS11Gi3PvLyMLaKt5XUlEJHW6nt75OtNWsVbeWRzo+0=,tag:mStLA2xxl917RKKxdwO0hQ==,type:str]
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:ZhH9cT2+oSmVsH5zjo/gs/Tk+qcLlg==,iv:rlY4pl0UaDMuFPYLH1bBgFHmUvDKNFeecglhDqNVKpw=,tag:MntzpKuRraBVA4z4AWW8nA==,type:str]
    GRAFANA_AUTH_CLIENT_ID: null
    GRAFANA_AUTH_CLIENT_SECRET: null
    #ENC[AES256_GCM,data:vPVHVn32g1VOP8MUTEOTfSS0s9HPnLk=,iv:gYC/dR08t7jVGECyCmielFEA21GJ1ZPVc2YoljgKSPI=,tag:UxTsVqaSoXALkf3KLPHedQ==,type:comment]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:LhIZ+IA2CPj7HktZ4IOqH7WKPqHsSIIFcf4GnqoUOnvis10mgsJXDwga1/eCIA==,iv:GeWz90Q3LBvxOoIB7YecRSgICmcSIYswep7XT0Y43Ys=,tag:IzxTEH3tuz+tiXPpzWSF4g==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:gPIW2TMIGG+vQSk=,iv:IYdsm4rM4F3WMWEt/W2lBNAT/+02SBUlQIg0w4b9r6E=,tag:leg2uS8tEt9cPS5/u8db7g==,type:str]
sops:
    lastmodified: "2026-05-20T07:55:54Z"
    mac: ENC[AES256_GCM,data:oqvPh9AVDvUNLwTaUaoIR9zWhrHJR0D9fC0dQU/UnPgfvbkrrmlsEV0NWCgYW6rlXqe2bZtozuxzt+RDMR8T2TNcGGiuvXXDW1Ta7fAWpyURbkAOLuPLoidAbP7UAczDYOI8rpnJ1hFUBXvlOTpORY16tdSHGRZW1d1YQstqXYM=,iv:ybw4nxA2ZJ0fS3R8H++kkBSmnZLxozebTmfNIL12b9o=,tag:zy8PEp93RcBt3uPzechjQA==,type:str]
    pgp:
        - created_at: "2026-05-20T07:55:54Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3McSkAh3rFhAQ/+LHfdkNXUjxteuqpzPhlvT8dC6S4twbWCyr3YoEuSrKd9
            fHE//QUiePEKOHfXAg6Z7lrt7b2K4r4MKz5ZHWyGj1Xgykf9keD2LEK4al/qZyPA
            oBpMBJhjb7ngCvIq1qPV2Oy300BS0nZJJ36zCg4jqifcUqQvWwbRjcrZmMVuE4iC
            vjF+N237cd/udLlH0nX/BYO1mVCFeOz3XL8I0pYxtcL9Htbg3dxQ6JDM1+jq4TbV
            E8uhMHNOvHsqT/ay4Ro7G2rEVQllXMYSNco12++RfY74t1ZJffqxLULUGhGTOpIW
            owxvEeEgX0B4XmVMHBo/jWr3+JqgC3sJGRXwwFmaI+nFwmxpQmm/x5tQiW5ndLLe
            4X0Lia0les/dFdrCdPru6QOlAlatjlqNrMLou6PgD23TXYANz9GwQayxTodYhVEM
            sM05IkYVnYTtaAbg/LJu26QqO0XDeYvRhVQf2+Hp35ZWHjdtcfqVMlpqWbl3A39h
            adaEW2HIbqOB/b5SqL203uxXsZgnhYP+S397jPStmUgRGyEzgtTI6AF8/aqMz32z
            wASnUiCey6abDavhQIKlqZA2ANU5EmvKNarazHELXjk5BFuX06aLaSditKamgQqt
            wqMUWIjK1xzme0lpJggZsM1f/ppn3jCxtZO8ykIpdR8ywC6v8LZwSSUeTyv/hV/U
            ZgEJAhD2GCev0WfBg0zscsBmsKKisIrJEs8tuW+S2Q48+1ToKPPj9/K7P+hC7ECw
            kjdEOFLaE6AK05WU2R0EqQMnnhM1MzvAB3P6tTrt+Pu3hQkZemFCUmwmjvjBNcJF
            RGu8V0jWFA==
            =2xNu
            -----END PGP MESSAGE-----
          fp: EF552EBA773641B396D26658E1F56350C447581E
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
