apiVersion: v1
kind: ConfigMap
metadata:
    name: environment-secrets
    namespace: flux-system
    annotations:
        kustomize.toolkit.fluxcd.io/ssa: merge
data:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:wnvfinaNS/eDWF/KPChI+jERpazyyDIw44eKplqysfyyeNcoihrFgg==,iv:rcXtdpG8Pd0JFSvp4/2jRYDIbPiH3qERU9ABP/dTs4w=,tag:dJclSlMAmp+e6d189YgbYg==,type:str]
    VALKEY_PASSWORD: ENC[AES256_GCM,data:38RlFnPIhCCgwEW83u/mu38yYbrCtA==,iv:eDXv65vOZPwvBuExRwbf0K2oxRzap9BFXtGQjALnNnI=,tag:nnMb7USiNdcPcMGtQhDJ+A==,type:str]
    GRAFANA_ADMIN_USER: ENC[AES256_GCM,data:/tFzIeA=,iv:PMl9j+dpB8GP28ig4whjczUwLhWtgcSrFy9hXLSaAfM=,tag:81RTnGJxz0PnG6vjeKtByA==,type:str]
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:O1fNCt3JmO/nnCm+3iULFPclk4YR6w==,iv:nnr+ow/wIlYCPy/oKmgNOhkV+0oYPKq72ILhNhvCdJk=,tag:khU4n6xHxBbOY9eFC648kA==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:Ij9WXY1V,iv:hinPrV4C3MraiwDkuZGMUbuL/XFTtm8m8JZw3cGYLyM=,tag:6q61MDbwGyt+fX4Oezi+GQ==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:J1ST7kc4,iv:nwda8k0AsO5/WZK9gNspBk05uzT4kvYwJb9YlVsJkOc=,tag:pcmaWo66z/s7wsLCzrcxtg==,type:str]
    KIALI_SIGNING_KEY: ENC[AES256_GCM,data:GoYh0bT7HHl/G7zEFK3vW0xSQ1kSsg==,iv:9p00XOUGP95q8M85oFoYE6PZ5DwMaW4Nd4pDWdf05kg=,tag:2inXga+fBq4ESGky3eVKoQ==,type:str]
    CNPG_ACCESS_KEY_ID: ENC[AES256_GCM,data:e2nW/QlsrACf26cFyJ5+A3PCri4=,iv:NdIQNT6mIuwqMfPRfGg7tAsxXJlfajvum6oxwpSoZvc=,tag:nMNTins/XkAyK9ZsHDtmbg==,type:str]
    CNPG_ACCESS_SECRET_KEY: ENC[AES256_GCM,data:aIMNoMMYHB/zT3eV3JomTRn/tt+URcXqRVXV+M1CtPEs7zo5pZCreg==,iv:ug94sa5Y8vDKNdyyj8aVkCGyS1VgVDin6qiIwJ+Jwx4=,tag:9/j+PC98fETcBpK+mbDi1Q==,type:str]
    DATABASE_USERNAME: ENC[AES256_GCM,data:OWhWqxsMEgI=,iv:N1YztzunGv+PrJR0DZDTib0eLubQMYF66v8VtIEHLPc=,tag:9FOeLy4VCKISTq3vRVViPA==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:xwlOSCt/UzhbmkoeXo+unA==,iv:EXb00xpCYUl56TGt03p04/6hp0//tebllbdyMv4kuzg=,tag:LkGfp5PGnM6c/Ds4JA9N5w==,type:str]
sops:
    lastmodified: "2026-03-02T10:21:21Z"
    mac: ENC[AES256_GCM,data:j3wcCh36BaU+omBf3NjYKLAZ8jFlQh8anb5ulxHWlDc+bYobcUWdRIKy4NrajjKShH23Fh7I43CW1yWSGxZ+Jbx3PgHcZWe3GMh9lXOpmtD9hzysYggPHb14mchSctP9YsqnoQU4j+Hdd6IXbzbDo5lSt59RcecUPm+SKsFPu70=,iv:hqLGX5+pRCIMkmZxU0zq1g/aEc5HwGOFyfdTphz/4Qg=,tag:ctP1EjQ3atA7Y9jFWxYEjQ==,type:str]
    pgp:
        - created_at: "2026-03-02T10:21:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3McSkAh3rFhAQ//a1+jEihNkfuDcVJySE5P4Y3w9BNTEUpJUo5IWg7SSLIV
            Wuh2STHbzj0JvhnVdPXzIT32uWQuZD1h6o6i7oCntZTm5kbJR9IWA9UDqSkrSO8m
            nIdE/0zPimevqb3qFgyseuzRpPMSQJumpSPkeXpzkbR6vpH7177IN3a723UTU0Jg
            43AOmlT15KsHUj00Std6shA0SqOnzodIWKXGGF98xJ9tqV2wlftgTy2uL8HvLwvD
            6wplC2U/t2BxvRBbzBY5SYFr8WWxJo777Rgc2pvuHabJE3ETJ6TVkWpm+0mE25nP
            jMU62PR5p47GKf41431w3ZnBUynYXI4FaPqJNBjAY4Dim2wURUPQqwIj/Tht8s5X
            JzFEl4TZIjDxnSUtdtWQD6DN59ElfUrQA/cReVBjPyRz4UTu7E6J5rX2uUvc9x+u
            /7gqui7cNrGJlqF/1m6y0H3fslvFTbLCPdBHEyJ3TCiqek0+UHIz67s9hjdPUBD/
            7AtyYB6np2hBmfWiH4jCwh+UJCslXs/L5Tg29+QvP49FQX6QZzNXJ5Vfs3jgquga
            ST3pWoFHJ5U+THoAFU8CIbWwtQCpAtpZZ0e7Xs+w9U/ArFmz1bwt1hz5XKdoTLlV
            aWwTzbh53Zazpv5DSINFhA1veWF3co158Wz0xdV8tJvDdKfyXZezx/cgpllp3dbU
            aAEJAhCYGvvHiTR0ZnO5zDfshQe1SKyUT6DVCU7Q4gd+ozuTCZvquOiW3dBAMooc
            BhsK6YafmbODaUQKFsYukLYUTc+PRJ3lKSuke7RvzNvjEEaeVCU1uMa/+qdNWm8m
            8DG2bSl2zjCD
            =qb5S
            -----END PGP MESSAGE-----
          fp: EF552EBA773641B396D26658E1F56350C447581E
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
