apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-operator
spec:
  releaseName: opentelemetry-operator
  chart:
    spec:
      chart: opentelemetry-operator
      version: 0.84.0
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
        namespace: observability
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: opentelemetry-operator-values
