apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kiali-server
spec:
  releaseName: kiali-server
  chart:
    spec:
      chart: kiali-server
      version: 2.7.1
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: observability
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: kiali-values
