apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jaeger
spec:
  releaseName: jaeger
  chart:
    spec:
      chart: jaeger
      version: 3.4.1 
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: observability
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: jaeger-values
