---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: observability
spec:
  releaseName: tempo
  chart:
    spec:
      chart: tempo-distributed
      version: 1.19.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: observability
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: tempo-values
