apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 0-envconfigs
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./environments/prod-nl/envconfigs
  prune: false
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 1-istio-system
  namespace: flux-system
spec:
  dependsOn:
    - name: 0-envconfigs
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./environments/common/istio/system
  prune: false
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: environment-configs
      - kind: ConfigMap
        name: environment-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 2-istio-ingress
  namespace: flux-system
spec:
  dependsOn:
    - name: 1-istio-system
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./environments/common/istio/ingress
  prune: false
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: environment-configs
      - kind: ConfigMap
        name: environment-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 3-prometheus-stack
  namespace: flux-system
spec:
  dependsOn:
    - name: 2-istio-ingress
  interval: 10m0s
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./environments/common/prometheus-stack
  prune: false
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: environment-configs
      - kind: ConfigMap
        name: environment-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 4-observability
  namespace: flux-system
spec:
  dependsOn:
    - name: 2-istio-ingress
    - name: 3-prometheus-stack
  interval: 10m0s
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./environments/common/observability
  prune: false
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: environment-configs
      - kind: ConfigMap
        name: environment-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 5-infra
  namespace: flux-system
spec:
  dependsOn:
    - name: 2-istio-ingress
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./environments/common/infra
  prune: false
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: environment-configs
      - kind: ConfigMap
        name: environment-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 6-data
  namespace: flux-system
spec:
  dependsOn:
    - name: 2-istio-ingress
    - name: 3-prometheus-stack
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./environments/common/data
  prune: false
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: environment-configs
      - kind: ConfigMap
        name: environment-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 7-envspecific
  namespace: flux-system
spec:
  dependsOn:
    - name: 0-envconfigs
    - name: 5-infra
    - name: 6-data
    - name: 2-istio-ingress
    - name: 4-observability
  interval: 10m0s
  wait: true
  timeout: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./environments/prod-nl/envspecific
  prune: false
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: environment-configs
      - kind: ConfigMap
        name: environment-secrets