apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pgbouncer
  namespace: cnpg  
spec:
  cluster:
    name: postgres

  instances: 3
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"

  monitoring:
    enablePodMonitor: true