apiVersion: v1
kind: Secret
metadata:
    name: onecloud-user
    namespace: cnpg
    annotations:
        kustomize.toolkit.fluxcd.io/ssa: merge
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Rv0AcU/6CdHlYqC+RpUm1+p3z/8=,iv:FLGAES632MVVo6XyWba02udTbshS/8ETnigXF7DUtRw=,tag:CDrvB2pSy55T1uMT6hiqqA==,type:str]
    password: ENC[AES256_GCM,data:xxjAGTTyq8q0kNn0SevUBvzfGiA=,iv:Bf2RpXltpQNmKgqf/48fIAAy/Qrx/N2ABIa+0ZD8ckE=,tag:wCIitk7ExtCOSTD8Lo8RIg==,type:str]
sops:
    lastmodified: "2026-02-27T14:00:52Z"
    mac: ENC[AES256_GCM,data:V2ikuuUy/rJdK90hfDV33g/iZU28FSGe90cueTLOWhEtC57xR2qJgmoaf9NWXLdTVa4F7VN6yvL4Xz8EnCV98iG4zre/o+XAsZHrTBWH6g3yIFX+KfLezIpAi7P23BYt5pDhGLPWTJzb9TM90hAEvBiNDb/6yTvhZI0EQtr6Vss=,iv:Vd3NQGRaW1OElKPLA4n4qdM8sqwUC+DzUmV7o7RjnMg=,tag:7UkvGRWEFxi0QH5k7f+L8A==,type:str]
    pgp:
        - created_at: "2026-02-27T14:00:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3McSkAh3rFhAQ/+InVBX0nDHeqHVVz19QUZnqr+E6ZsjCzEtGgQ0KUQABtU
            OOsTvK7MFmzARwZqNN1GHwwwoYNuoN9swEW58ferBDcp5McPJ4NKbb9bt+PzyTa7
            UF/wySV0Pjiu9MonEE71VdW/Hb6bZJCmp4Nu3Tar3lq4WHh0Ot4D38VmU2UAgGJV
            PHqFnx+O2li/VO9SHeuUprFeRSjgETWFCDDmHVM9du8JcZTPwsicEd9TyjlcNGbP
            S6XKxzf+OQt/ejdyUBTEf3E0qr2tnQfP316Svv5H1m76ff68T1I/1Q+dsHiSW6XK
            /wywHg2K6XFZNcogAlHZ+jFTWR7x+uwPd1bLulIQtq9xL+JQJsuVM6KlZTsSHsNI
            mcJFabnBqJmyDbudAZWTFKHUXwY06gDHTxlvnK7SKZSWamATLt0J2m0DbroRvSr7
            4CqJqpHGSM7Dilb7Hzrj9s/+RqPbbSI8LvrBSxghQHP2Jvsa+xDZnG1W/5Aoz3t8
            W/kTpP4GIgLHZ2CFT8OHwlclPkCmdkBNYFPoU1cNOe+qrOnQy1DUpROxLzM4mWOD
            GKdXWRXuCNd60JLvkAwtqFaWPtxXKQyLkjvO8bjeFRs+E8QGecbi63IhCIIIv/T9
            vQvJX/auDvXJq9a8QmnHRbLElsonfUn7cfS8qaaB2i/pLY4brLafd4c0rEtIia7U
            aAEJAhBo0GuBK48QHPz6AgBXuzq9jp9AYWVREaJ+vzT1N7aNI2fSi+X1FYAKg5uc
            v9DGcfi1zEMu2MT3znYAPBtXGF1BJG5SkQf6cTAP541cX7wlS8ax6grPO7sHVQc5
            AqhXNJsARNh+
            =Ydw+
            -----END PGP MESSAGE-----
          fp: EF552EBA773641B396D26658E1F56350C447581E
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
